//-----------------------------------------------------------------------------
// Engineer:      Auto-converted from ESL test_noc_sim.cpp
// Create Date:   2026/04/02
// Design Name:   HybridAcc Testbench
// Module Name:   tb_noc_sim
// Project Name:  HybridAcc
// Target Devices: ASIC
// Tool Versions: Synopsys VCS W-2024.09-SP1
// Description:   Full-system NoC simulation testbench — reads the same
//                binary test data generated by the Python/ESL toolflow
//                (config.txt, scan_chain.bin, input_activation.bin,
//                input_weight.bin, input_partial_sum.bin, pe_program.bin,
//                output_partial_sum.bin) and drives the RTL NetworkOnChip
//                DUT through the four NoC planes (PS, PD, PLI, PLO).
//                Supports both conv2d and gemm modes, normal and ultra,
//                temporal wave tiling, and verification with cosine
//                similarity / MSE.
//
//                Usage (VCS):
//                  +DATA_DIR=<path>        Test-data directory
//                  +VERIFY_TOL=<float>     Mismatch tolerance (default 0.02)
//                  +CLOCK_PERIOD_NS=<int>  Clock period (default 10)
//                  +VERBOSE=1              Enable verbose logging
//                  +PROGRESS_INTERVAL=N    Print PLI/PLO progress every N pkts (default 1000)
//                  +IDLE_TIMEOUT=N         Abort if no data transfer for N cycles (0=off)
//
// Dependencies:  tb_common.svh, hybridacc_utils_pkg.sv, NetworkOnChip.sv
//                (and its sub-hierarchy: NoCRouter, MBUS, PE, FIFO, …)
//-----------------------------------------------------------------------------
`include "../tb_common.svh"
`include "../../src/hybridacc_utils_pkg.sv"
`ifndef GATE_SIM
`include "../../src/FIFO.sv"
`include "../../src/asyncFIFO.sv"
`include "../../src/PE/InstructionMemory.sv"
`include "../../src/PE/Decoder.sv"
`include "../../src/PE/LoopController.sv"
`include "../../src/PE/TransformRegFile.sv"
`include "../../src/PE/VMULU.sv"
`include "../../src/PE/VADDU.sv"
`include "../../src/PE/LDMA.sv"
`include "../../src/PE/SDMA.sv"
`include "../../src/PE/DataMemory.sv"
`include "../../src/PE/PsumRegFile.sv"
`include "../../src/PE/PErouter.sv"
`include "../../src/PE/IF_ID_Stage.sv"
`include "../../src/PE/EXE_M_Stage.sv"
`include "../../src/PE/EXE_A_Stage.sv"
`include "../../src/PE/ProcessElement.sv"
`include "../../src/NoC/NoCRouter.sv"
`include "../../src/NoC/MBUS.sv"
`include "../../src/NetworkOnChip.sv"
`endif

module tb_noc_sim;
    import hybridacc_utils_pkg::*;

    // =========================================================================
    // Parameters (matching ESL)
    // =========================================================================
    localparam int unsigned NUM_PORTS        = 3;
    localparam int unsigned PORT_WIDTH_BITS  = 64;
    localparam int unsigned NUM_PES_PER_PORT = 16;
    localparam int unsigned TOTAL_PES        = NUM_PORTS * NUM_PES_PER_PORT;
    localparam int unsigned TDW              = NUM_PORTS * PORT_WIDTH_BITS; // 192
    localparam int unsigned MAX_WAIT_CYCLES  = 10000;
    localparam int unsigned MAX_DATA_SIZE    = 4 * 1024 * 1024; // 4M entries max

    // =========================================================================
    // Clock / Reset
    // =========================================================================
    logic clk, reset_n;
    tb_clock_reset clk_rst(.clk(clk), .reset_n(reset_n));

    // =========================================================================
    // DUT signals
    // =========================================================================
    logic        command_mode;
    logic [31:0] command_data;

    // PS
    logic [TDW-1:0] noc_ps_in_data;
    logic [15:0]    noc_ps_in_addr;
    logic [63:0]    noc_ps_in_mask;
    logic           noc_ps_in_valid, noc_ps_in_ready;
    // PD
    logic [TDW-1:0] noc_pd_in_data;
    logic [15:0]    noc_pd_in_addr;
    logic [63:0]    noc_pd_in_mask;
    logic           noc_pd_in_valid, noc_pd_in_ready;
    // PLI
    logic [TDW-1:0] noc_pli_in_data;
    logic [15:0]    noc_pli_in_addr;
    logic [63:0]    noc_pli_in_mask;
    logic           noc_pli_in_valid, noc_pli_in_ready;
    // PLO request
    noc_addr_req_t  noc_plo_in_data;
    logic           noc_plo_in_valid, noc_plo_in_ready;
    // PLO response
    logic [TDW-1:0]       noc_plo_out_data;
    NOC_RESPONSE_STATUS   noc_plo_out_status;
    logic                 noc_plo_out_valid, noc_plo_out_ready;

`ifdef GATE_SIM
    // Flat-wire intermediates for struct/enum ports (gate netlist uses plain wires)
    wire [$bits(noc_addr_req_t)-1:0] g_noc_plo_in_data;
    wire [1:0]                        g_noc_plo_out_status;
    assign g_noc_plo_in_data   = noc_plo_in_data;
    assign noc_plo_out_status  = NOC_RESPONSE_STATUS'(g_noc_plo_out_status);
`endif

`ifdef GATE_SIM
    // Load sdf for gate-level timing simulation
    initial begin
        $display("[TB] Loading SDF for gate-level simulation...");
        $sdf_annotate("syn/NetworkOnChip/NetworkOnChip.sdf", noc);
    end
`endif

    // =========================================================================
    // DUT instantiation
    // =========================================================================
`ifdef GATE_SIM
    NetworkOnChip noc (
`else
    NetworkOnChip #(
        .NUM_PORTS       (NUM_PORTS),
        .PORT_WIDTH_BITS (PORT_WIDTH_BITS),
        .NUM_PES_PER_PORT(NUM_PES_PER_PORT),
        .PE_FIFO_DEPTH   (4),
        .NOC_FIFO_DEPTH  (4)
    ) noc (
`endif
        .clk            (clk),
        .reset_n        (reset_n),
        .command_mode   (command_mode),
        .command_data   (command_data),
        .noc_ps_in_data (noc_ps_in_data),
        .noc_ps_in_addr (noc_ps_in_addr),
        .noc_ps_in_mask (noc_ps_in_mask),
        .noc_ps_in_valid(noc_ps_in_valid),
        .noc_ps_in_ready(noc_ps_in_ready),
        .noc_pd_in_data (noc_pd_in_data),
        .noc_pd_in_addr (noc_pd_in_addr),
        .noc_pd_in_mask (noc_pd_in_mask),
        .noc_pd_in_valid(noc_pd_in_valid),
        .noc_pd_in_ready(noc_pd_in_ready),
        .noc_pli_in_data (noc_pli_in_data),
        .noc_pli_in_addr (noc_pli_in_addr),
        .noc_pli_in_mask (noc_pli_in_mask),
        .noc_pli_in_valid(noc_pli_in_valid),
        .noc_pli_in_ready(noc_pli_in_ready),
    `ifdef GATE_SIM
        .noc_plo_in_data (g_noc_plo_in_data),
    `else
        .noc_plo_in_data (noc_plo_in_data),
    `endif
        .noc_plo_in_valid(noc_plo_in_valid),
        .noc_plo_in_ready(noc_plo_in_ready),
        .noc_plo_out_data  (noc_plo_out_data),
    `ifdef GATE_SIM
        .noc_plo_out_status(g_noc_plo_out_status),
    `else
        .noc_plo_out_status(noc_plo_out_status),
    `endif
        .noc_plo_out_valid (noc_plo_out_valid),
        .noc_plo_out_ready (noc_plo_out_ready)
    );

    // =========================================================================
    // Test data storage
    // =========================================================================
    logic [31:0]  scan_chain_data [];
    logic [15:0]  input_activation[];
    logic [15:0]  input_weight    [];
    logic [15:0]  input_partial_sum[];
    logic [15:0]  expected_output [];
    logic [15:0]  output_partial_sum[];
    logic [15:0]  pe_program      [];

    // =========================================================================
    // Config key-value store
    // =========================================================================
    string cfg_keys   [256];
    string cfg_values [256];
    int    cfg_count = 0;

    // =========================================================================
    // Conv2D / GEMM parameter structs
    // =========================================================================
    // Conv2D
    int kernel_size, in_ch, out_ch, in_height, in_width, out_height, out_width, stride_val;
    bit partial_sum_zero, ultra_mode_flag;
    int temporal_wave_count, temporal_wave_out_h, temporal_wave_out_ch, temporal_wave_in_ch;

    // GEMM
    int gemm_M, gemm_N, gemm_K;
    int grid_m, grid_n, grid_k;
    int pe_m, pe_n, pe_k;
    bit gemm_partial_sum_zero, gemm_ultra_mode;
    int wave_m, wave_n, wave_k;
    int grid_m_per_wave [64];
    int grid_n_per_wave [64];
    int grid_k_per_wave [64];
    int grid_m_per_wave_len, grid_n_per_wave_len, grid_k_per_wave_len;

    // Mode string
    string mode_str;

    // Response metadata FIFO (implemented as arrays)
    typedef struct {
        longint unsigned base_idx;
        bit              ultra;
        longint unsigned per_port_stride;
        int unsigned     ports;
    } resp_meta_t;

    resp_meta_t rx_meta_fifo [1024];
    int rx_meta_wr_ptr = 0;
    int rx_meta_rd_ptr = 0;

    // Statistics
    longint unsigned total_sent_bytes;
    longint unsigned total_received_bytes;
    longint unsigned total_macs;

    // Synchronisation events
    event start_traffic_ev;
    event data_loaded_ev;
    event scan_chain_done_ev;
    event program_done_ev;
    event pe_start_done_ev;
    event ps_done_ev, pd_done_ev, pli_done_ev, plo_done_ev;

    // Verbose flag
    int verbose = 0;

    // Tolerance
    real verify_tolerance = 0.02;

    // Done flags (for join-like behaviour)
    bit ps_finished = 0, pd_finished = 0, pli_finished = 0, plo_finished = 0;

    // Progress tracking counters
    longint unsigned ps_pkt_count  = 0;
    longint unsigned pd_pkt_count  = 0;
    longint unsigned pli_pkt_count = 0;
    longint unsigned plo_req_count = 0;
    longint unsigned plo_resp_count = 0;
    int unsigned     progress_interval = 1000;
    int unsigned     idle_timeout_cycles = 0;

    // =========================================================================
    // Config parsing
    // =========================================================================
    function automatic int cfg_get_int(string key, int default_val = 0);
        for (int i = 0; i < cfg_count; i++) begin
            if (cfg_keys[i] == key) begin
                return cfg_values[i].atoi();
            end
        end
        return default_val;
    endfunction

    function automatic bit cfg_get_bool(string key, bit default_val = 0);
        for (int i = 0; i < cfg_count; i++) begin
            if (cfg_keys[i] == key) begin
                if (cfg_values[i] == "True" || cfg_values[i] == "true" || cfg_values[i] == "1")
                    return 1;
                else
                    return 0;
            end
        end
        return default_val;
    endfunction

    function automatic string cfg_get_str(string key, string default_val = "");
        for (int i = 0; i < cfg_count; i++) begin
            if (cfg_keys[i] == key) return cfg_values[i];
        end
        return default_val;
    endfunction

    // Parse "[1, 2, 3]" style list into int array, return count
    function automatic int cfg_get_list_int(string key, output int arr[64]);
        string raw;
        int cnt = 0;
        raw = cfg_get_str(key, "");
        if (raw.len() == 0) return 0;
        begin
            // Strip brackets and parse comma-separated ints
            automatic string cleaned = "";
            automatic int val = 0;
            automatic bit in_num = 0;
            automatic bit neg = 0;
            for (int i = 0; i < raw.len(); i++) begin
                byte c = raw.getc(i);
                if (c == "-") begin
                    neg = 1;
                end else if (c >= "0" && c <= "9") begin
                    val = val * 10 + (c - "0");
                    in_num = 1;
                end else begin
                    if (in_num) begin
                        arr[cnt] = neg ? -val : val;
                        cnt++;
                        val = 0;
                        in_num = 0;
                        neg = 0;
                    end
                end
            end
            if (in_num) begin
                arr[cnt] = neg ? -val : val;
                cnt++;
            end
        end
        return cnt;
    endfunction

    // =========================================================================
    // Config file reader (key:value per line)
    // =========================================================================
    task automatic load_config(string path);
        int fd;
        string line_str;
        fd = $fopen(path, "r");
        if (fd == 0) begin
            $error("[TB] Cannot open config: %s", path);
            $finish;
        end
        cfg_count = 0;
        while (!$feof(fd)) begin
            automatic string key_s, val_s;
            automatic int colon_pos = -1;
            if ($fgets(line_str, fd) == 0) continue;
            // Trim trailing newline
            while (line_str.len() > 0 && (line_str.getc(line_str.len()-1) == "\n" ||
                                           line_str.getc(line_str.len()-1) == "\r"))
                line_str = line_str.substr(0, line_str.len()-2);
            if (line_str.len() == 0) continue;
            // Find first ':'
            for (int i = 0; i < line_str.len(); i++) begin
                if (line_str.getc(i) == ":") begin
                    colon_pos = i;
                    break;
                end
            end
            if (colon_pos <= 0) continue;
            key_s = line_str.substr(0, colon_pos - 1);
            val_s = line_str.substr(colon_pos + 1, line_str.len() - 1);
            cfg_keys[cfg_count]   = key_s;
            cfg_values[cfg_count] = val_s;
            cfg_count++;
        end
        $fclose(fd);
    endtask

    // =========================================================================
    // Binary file loader (16-bit elements)
    // =========================================================================
    task automatic load_binary_fp16(string path, ref logic [15:0] arr[]);
        int fd;
        int file_size;
        int num_elements;
        byte unsigned byte_buf;
        fd = $fopen(path, "rb");
        if (fd == 0) begin
            $error("[TB] Cannot open binary file: %s", path);
            $finish;
        end
        // Determine file size
        file_size = 0;
        while (!$feof(fd)) begin
            if ($fread(byte_buf, fd) == 0) break;
            file_size++;
        end
        $fclose(fd);
        num_elements = file_size / 2;
        arr = new[num_elements];
        fd = $fopen(path, "rb");
        for (int i = 0; i < num_elements; i++) begin
            automatic byte unsigned lo, hi;
            void'($fread(lo, fd));
            void'($fread(hi, fd));
            arr[i] = {hi, lo}; // little-endian
        end
        $fclose(fd);
    endtask

    // Binary file loader (32-bit elements)
    task automatic load_binary_i32(string path, ref logic [31:0] arr[]);
        int fd;
        int file_size;
        int num_elements;
        byte unsigned byte_buf;
        fd = $fopen(path, "rb");
        if (fd == 0) begin
            $error("[TB] Cannot open binary file: %s", path);
            $finish;
        end
        file_size = 0;
        while (!$feof(fd)) begin
            if ($fread(byte_buf, fd) == 0) break;
            file_size++;
        end
        $fclose(fd);
        num_elements = file_size / 4;
        arr = new[num_elements];
        fd = $fopen(path, "rb");
        for (int i = 0; i < num_elements; i++) begin
            automatic byte unsigned b0, b1, b2, b3;
            void'($fread(b0, fd));
            void'($fread(b1, fd));
            void'($fread(b2, fd));
            void'($fread(b3, fd));
            arr[i] = {b3, b2, b1, b0}; // little-endian
        end
        $fclose(fd);
    endtask

    // =========================================================================
    // FP16 ↔ real conversion helpers
    // =========================================================================
    function automatic real fp16_to_real(logic [15:0] h);
        automatic int sign_bit = h[15];
        automatic int exp_bits = h[14:10];
        automatic int mant_bits = h[9:0];
        automatic real mantissa, result;
        if (exp_bits == 0 && mant_bits == 0) return 0.0;
        if (exp_bits == 5'h1F) begin
            if (mant_bits != 0) return 0.0; // NaN → 0
            return (sign_bit ? -1.0e30 : 1.0e30); // Inf
        end
        if (exp_bits == 0) begin
            // Denormalized
            mantissa = $itor(mant_bits) / 1024.0;
            result = mantissa * (2.0 ** (-14));
        end else begin
            mantissa = 1.0 + $itor(mant_bits) / 1024.0;
            result = mantissa * (2.0 ** (exp_bits - 15));
        end
        return sign_bit ? -result : result;
    endfunction

    // =========================================================================
    // Ceil-division
    // =========================================================================
    function automatic int ceil_div(int a, int b);
        if (b == 0) return 0;
        return (a + b - 1) / b;
    endfunction

    // =========================================================================
    // Wave range helpers (matching ESL get_wave_range / get_wave_tile_range)
    // =========================================================================
    function automatic void get_wave_range(int total, int waves, int wave_idx,
                                           output int w_start, output int w_end);
        automatic int chunk;
        if (waves <= 0) begin w_start = 0; w_end = total; return; end
        chunk = ceil_div(total, waves);
        w_start = wave_idx * chunk;
        if (w_start >= total) begin w_start = total; w_end = total; return; end
        w_end = w_start + chunk;
        if (w_end > total) w_end = total;
    endfunction

    function automatic void get_wave_tile_range(
        int tiles_per_wave[], int tiles_len,
        int wave_idx, int total_tiles, int fallback_waves,
        output int w_start, output int w_end);
        if (tiles_len == 0) begin
            get_wave_range(total_tiles, fallback_waves, wave_idx, w_start, w_end);
            return;
        end
        if (wave_idx < 0 || wave_idx >= tiles_len) begin
            w_start = total_tiles; w_end = total_tiles; return;
        end
        w_start = 0;
        for (int i = 0; i < wave_idx; i++) w_start += tiles_per_wave[i];
        w_end = w_start + tiles_per_wave[wave_idx];
        if (w_start > total_tiles) w_start = total_tiles;
        if (w_end > total_tiles) w_end = total_tiles;
    endfunction

    // =========================================================================
    // Index helpers (matching ESL Index2D, Index3D, Index4D)
    // =========================================================================
    function automatic int idx2d(int d0, int d1, int r, int c);
        // (r, c) in shape [d0][d1]
        return r * d1 + c;
    endfunction

    function automatic int idx3d(int d0, int d1, int d2, int a, int b, int c);
        return (a * d1 + b) * d2 + c;
    endfunction

    function automatic int idx4d(int d0, int d1, int d2, int d3, int a, int b, int c, int d);
        return ((a * d1 + b) * d2 + c) * d3 + d;
    endfunction

    // =========================================================================
    // Meta-FIFO helpers
    // =========================================================================
    function automatic int meta_fifo_num_free();
        return 1024 - ((rx_meta_wr_ptr - rx_meta_rd_ptr + 1024) % 1024);
    endfunction

    task automatic meta_fifo_push(resp_meta_t m);
        rx_meta_fifo[rx_meta_wr_ptr % 1024] = m;
        rx_meta_wr_ptr++;
    endtask

    function automatic bit meta_fifo_try_pop(output resp_meta_t m);
        if (rx_meta_rd_ptr == rx_meta_wr_ptr) return 0;
        m = rx_meta_fifo[rx_meta_rd_ptr % 1024];
        rx_meta_rd_ptr++;
        return 1;
    endfunction

    function automatic int meta_fifo_available();
        return rx_meta_wr_ptr - rx_meta_rd_ptr;
    endfunction

    // =========================================================================
    // Command bus helper (matching ESL send_command)
    // =========================================================================
    task automatic send_command(message_command_t cmd, logic [31:0] param = 0);
        automatic logic [31:0] cmd_data_val;
        cmd_data_val = (param & 32'hFFFFFFF0) | ({28'd0, cmd} & 32'h0000000F);
        command_mode <= 1'b1;
        command_data <= cmd_data_val;
        @(posedge clk);
        command_mode <= 1'b0;
    endtask

    // =========================================================================
    // Valid-ready handshake helpers
    // =========================================================================
    task automatic wait_ready_ps(int timeout = MAX_WAIT_CYCLES * 100);
        automatic int waited = 0;
        while (!noc_ps_in_ready && waited < timeout) begin
            @(posedge clk);
            waited++;
        end
        if (waited >= timeout) begin
            $error("[TB] Timeout waiting ready on noc_ps");
            $finish;
        end
    endtask

    task automatic wait_ready_pd(int timeout = MAX_WAIT_CYCLES * 100);
        automatic int waited = 0;
        while (!noc_pd_in_ready && waited < timeout) begin
            @(posedge clk);
            waited++;
        end
        if (waited >= timeout) begin
            $error("[TB] Timeout waiting ready on noc_pd");
            $finish;
        end
    endtask

    task automatic wait_ready_pli(int timeout = MAX_WAIT_CYCLES * 100);
        automatic int waited = 0;
        while (!noc_pli_in_ready && waited < timeout) begin
            @(posedge clk);
            waited++;
        end
        if (waited >= timeout) begin
            $error("[TB] Timeout waiting ready on noc_pli");
            $finish;
        end
    endtask

    task automatic wait_ready_plo(int timeout = MAX_WAIT_CYCLES * 100);
        automatic int waited = 0;
        while (!noc_plo_in_ready && waited < timeout) begin
            @(posedge clk);
            waited++;
        end
        if (waited >= timeout) begin
            $error("[TB] Timeout waiting ready on noc_plo");
            $finish;
        end
    endtask

    // =========================================================================
    // Data send helpers (matching ESL send_data_ps/pd/pli, recv_data_plo)
    // =========================================================================
    task automatic send_data_ps(logic [15:0] tag, logic [TDW-1:0] data_val,
                                bit is_ultra = 0, logic [63:0] mask = 64'hF);
        noc_ps_in_data <= data_val;
        noc_ps_in_addr <= (tag & 16'h003F) | (is_ultra ? 16'h0040 : 16'h0000);
        noc_ps_in_mask <= mask;
        noc_ps_in_valid <= 1'b1;
        @(posedge clk);
        wait_ready_ps();
        noc_ps_in_valid <= 1'b0;
        total_sent_bytes += (is_ultra ? (8 * NUM_PORTS) : 8);
        ps_pkt_count++;
    endtask

    task automatic send_data_pd(logic [15:0] tag, logic [TDW-1:0] data_val,
                                bit is_ultra = 0, logic [63:0] mask = 64'hF);
        noc_pd_in_data <= data_val;
        noc_pd_in_addr <= (tag & 16'h003F) | (is_ultra ? 16'h0040 : 16'h0000);
        noc_pd_in_mask <= mask;
        noc_pd_in_valid <= 1'b1;
        @(posedge clk);
        wait_ready_pd();
        noc_pd_in_valid <= 1'b0;
        total_sent_bytes += (is_ultra ? (8 * NUM_PORTS) : 8);
        pd_pkt_count++;
    endtask

    task automatic send_data_pli(logic [15:0] tag, logic [TDW-1:0] data_val,
                                 bit is_ultra = 0, logic [63:0] mask = 64'hF);
        noc_pli_in_data <= data_val;
        noc_pli_in_addr <= (tag & 16'h003F) | (is_ultra ? 16'h0040 : 16'h0000);
        noc_pli_in_mask <= mask;
        noc_pli_in_valid <= 1'b1;
        @(posedge clk);
        wait_ready_pli();
        noc_pli_in_valid <= 1'b0;
        total_sent_bytes += (is_ultra ? (8 * NUM_PORTS) : 8);
        pli_pkt_count++;
        if (pli_pkt_count % progress_interval == 0)
            $display("[PLI  Progress] %0d pkts sent | total TX %s @ %0t",
                     pli_pkt_count, format_si($itor(total_sent_bytes), "B"), $time);
    endtask

    task automatic recv_data_plo(logic [15:0] tag, longint unsigned base_idx,
                                 bit is_ultra = 0, longint unsigned per_port_stride = 0,
                                 int unsigned ports = NUM_PORTS);
        automatic resp_meta_t meta;
        noc_plo_in_data.addr <= (tag & 16'h003F) | (is_ultra ? 16'h0040 : 16'h0000);
        noc_plo_in_valid <= 1'b1;
        @(posedge clk);
        wait_ready_plo();
        noc_plo_in_valid <= 1'b0;
        meta.base_idx = base_idx;
        meta.ultra = is_ultra;
        meta.per_port_stride = per_port_stride;
        meta.ports = ports;
        meta_fifo_push(meta);
        total_received_bytes += (is_ultra ? (8 * NUM_PORTS) : 8);
        plo_req_count++;
        if (plo_req_count % progress_interval == 0)
            $display("[PLO  Progress] %0d reqs sent | total RX %s @ %0t",
                     plo_req_count, format_si($itor(total_received_bytes), "B"), $time);
    endtask

    // =========================================================================
    // Load all test data
    // =========================================================================
    task automatic load_test_data(string data_dir);
        $display("[TB] Loading test data from %s", data_dir);
        load_config({data_dir, "/config.txt"});
        load_binary_i32({data_dir, "/scan_chain.bin"}, scan_chain_data);
        load_binary_fp16({data_dir, "/input_activation.bin"}, input_activation);
        load_binary_fp16({data_dir, "/input_weight.bin"}, input_weight);
        load_binary_fp16({data_dir, "/input_partial_sum.bin"}, input_partial_sum);
        load_binary_fp16({data_dir, "/output_partial_sum.bin"}, expected_output);
        load_binary_fp16({data_dir, "/pe_program.bin"}, pe_program);

        output_partial_sum = new[expected_output.size()];
        for (int i = 0; i < expected_output.size(); i++) output_partial_sum[i] = 16'h0;

        $display("[TB] Data loaded.");
        $display("  Scan Chain : %0d entries", scan_chain_data.size());
        $display("  Activation : %0d elements", input_activation.size());
        $display("  Weight     : %0d elements", input_weight.size());
        $display("  Partial Sum: %0d elements", input_partial_sum.size());
        $display("  Expected   : %0d elements", expected_output.size());
        $display("  PE program : %0d instructions", pe_program.size());
    endtask

    // =========================================================================
    // Parse params from config
    // =========================================================================
    task automatic parse_conv_params();
        kernel_size          = cfg_get_int("kernel_size");
        in_ch                = cfg_get_int("in_ch");
        out_ch               = cfg_get_int("out_ch");
        in_height            = cfg_get_int("in_height");
        in_width             = cfg_get_int("in_width");
        out_height           = cfg_get_int("out_height");
        out_width            = cfg_get_int("out_width");
        stride_val           = cfg_get_int("stride");
        partial_sum_zero     = cfg_get_bool("partial_sum_zero");
        ultra_mode_flag      = cfg_get_bool("ultra_mode");
        temporal_wave_count  = cfg_get_int("temporal_wave_count");
        temporal_wave_out_h  = cfg_get_int("temporal_wave_out_h");
        temporal_wave_out_ch = cfg_get_int("temporal_wave_out_ch");
        temporal_wave_in_ch  = cfg_get_int("temporal_wave_in_ch");
    endtask

    task automatic parse_gemm_params();
        gemm_M              = cfg_get_int("M");
        gemm_N              = cfg_get_int("N");
        gemm_K              = cfg_get_int("K");
        grid_m              = cfg_get_int("grid_m", 1);
        grid_n              = cfg_get_int("grid_n", 1);
        grid_k              = cfg_get_int("grid_k", 1);
        pe_m                = cfg_get_int("pe_m", 12);
        pe_n                = cfg_get_int("pe_n", 8);
        pe_k                = cfg_get_int("pe_k", 32);
        gemm_partial_sum_zero = cfg_get_bool("partial_sum_zero");
        gemm_ultra_mode     = cfg_get_bool("ultra_mode");
        wave_m              = cfg_get_int("wave_m", 1);
        wave_n              = cfg_get_int("wave_n", 1);
        wave_k              = cfg_get_int("wave_k", 1);
        grid_m_per_wave_len = cfg_get_list_int("grid_m_per_wave", grid_m_per_wave);
        grid_n_per_wave_len = cfg_get_list_int("grid_n_per_wave", grid_n_per_wave);
        grid_k_per_wave_len = cfg_get_list_int("grid_k_per_wave", grid_k_per_wave);
    endtask

    // =========================================================================
    // Configure scan chain (matching ESL configure_scan_chain)
    // =========================================================================
    task automatic configure_scan_chain();
        $display("[TB] Configuring Scan Chain...");
        for (int i = scan_chain_data.size() - 1; i >= 0; i--) begin
            send_command(CMD_NOC_SCAN_CHAIN, scan_chain_data[i]);
        end
        repeat (3) @(posedge clk); // Wait for configuration to take effect
    endtask

    // =========================================================================
    // Load PE program (matching ESL load_pe_program)
    // =========================================================================
    task automatic load_pe_program_task();
        if (pe_program.size() == 0) begin
            $error("[TB] No PE program loaded!");
            return;
        end
        $display("[TB] Loading PE Program (%0d instructions)...", pe_program.size());
        for (int i = 0; i < pe_program.size(); i++) begin
            automatic logic [31:0] param;
            automatic logic [11:0] im_addr;
            automatic logic [15:0] im_data;
            im_addr = (i * 2) & PE_ROUTER_IM_ADDR_MASK;
            im_data = pe_program[i] & PE_ROUTER_IM_DATA_MASK;
            param = 32'h0;
            param = param | ({20'd0, im_addr} << PE_ROUTER_IM_ADDR_OFFSET);
            param = param | ({16'd0, im_data} << PE_ROUTER_IM_DATA_OFFSET);
            send_command(CMD_LOAD_PROGRAM, param);
        end
    endtask

    // =========================================================================
    // Response sink (matching ESL response_sink) — always-running process
    // =========================================================================
    initial begin : response_sink
        automatic resp_meta_t meta;
        automatic logic [TDW-1:0] resp_data;
        automatic int resp_count = 0;
        // Wait for traffic to start
        @(start_traffic_ev);

        forever begin
            noc_plo_out_ready <= (meta_fifo_num_free() > 0) ? 1'b1 : 1'b0;
            @(posedge clk);
            if (noc_plo_out_valid && noc_plo_out_ready) begin
                resp_data = noc_plo_out_data;
                resp_count++;
                plo_resp_count++;
                if (plo_resp_count % progress_interval == 0)
                    $display("[PLO  Resp    ] %0d responses received @ %0t", plo_resp_count, $time);
            if (meta_fifo_try_pop(meta)) begin
                    if (mode_str == "gemm") begin
                        // GEMM response handling
                        automatic int N_val = gemm_N;
                        if (!meta.ultra) begin
                            for (int w = 0; w < 4; w++) begin
                                automatic longint unsigned idx_val;
                                idx_val = meta.base_idx + w * N_val;
                                if (idx_val < output_partial_sum.size()) begin
                                    output_partial_sum[idx_val] = resp_data[(w*16) +: 16];
                                end
                            end
                        end else begin
                            for (int port = 0; port < meta.ports; port++) begin
                                automatic logic [63:0] chunk;
                                chunk = resp_data[(64*port) +: 64];
                                for (int och_off = 0; och_off < 4; och_off++) begin
                                    automatic longint unsigned idx_val;
                                    idx_val = meta.base_idx + port * meta.per_port_stride + och_off * N_val;
                                    if (idx_val < output_partial_sum.size()) begin
                                        output_partial_sum[idx_val] = chunk[(och_off*16) +: 16];
                                    end
                                end
                            end
                        end
                    end else begin
                        // Conv2D response handling
                        if (!meta.ultra) begin
                            for (int och_off = 0; och_off < 4; och_off++) begin
                                automatic longint unsigned idx_val;
                                idx_val = meta.base_idx + och_off;
                                if (idx_val < output_partial_sum.size()) begin
                                    output_partial_sum[idx_val] = resp_data[(och_off*16) +: 16];
                                end
                            end
                        end else begin
                            for (int port = 0; port < meta.ports; port++) begin
                                automatic logic [63:0] chunk;
                                chunk = resp_data[(64*port) +: 64];
                                for (int och_off = 0; och_off < 4; och_off++) begin
                                    automatic longint unsigned idx_val;
                                    idx_val = meta.base_idx + port * meta.per_port_stride + och_off;
                                    if (idx_val < output_partial_sum.size()) begin
                                        output_partial_sum[idx_val] = chunk[(och_off*16) +: 16];
                                    end
                                end
                            end
                        end
                    end
                end else begin
                    $warning("[TB] Received response but no metadata logged!");
                end
            end
        end
    end

    // =========================================================================
    // Conv2D distribution tasks
    // =========================================================================
    task automatic distribute_conv2d_ps();
        automatic int wave_out_h_val  = (temporal_wave_out_h  > 1) ? temporal_wave_out_h  : 1;
        automatic int wave_out_ch_val = (temporal_wave_out_ch > 1) ? temporal_wave_out_ch : 1;
        automatic int wave_in_ch_val  = (temporal_wave_in_ch  > 1) ? temporal_wave_in_ch  : 1;
        automatic int loop_out_h = ultra_mode_flag ? (out_height / NUM_PORTS) : out_height;
        automatic int channels_per_pkt = ultra_mode_flag ? 4 : 12;
        $display("[TB-NoC-PS] Distributing Conv2D Weights...");

        for (int wave_h = 0; wave_h < wave_out_h_val; wave_h++) begin
            automatic int oh_start, oh_end, ih_start, ih_end_val;
            automatic int loop_in_h = ultra_mode_flag ? (in_height / NUM_PORTS) : in_height;
            get_wave_range(loop_out_h, wave_out_h_val, wave_h, oh_start, oh_end);
            if (oh_start >= oh_end) continue;
            ih_start = oh_start * stride_val;
            ih_end_val = oh_end * stride_val + kernel_size - 1;
            if (ih_end_val > loop_in_h) ih_end_val = loop_in_h;

            for (int wave_oc = 0; wave_oc < wave_out_ch_val; wave_oc++) begin
                automatic int och_start, och_end;
                get_wave_range(out_ch, wave_out_ch_val, wave_oc, och_start, och_end);
                if (och_start >= och_end) continue;

                for (int wave_ic = 0; wave_ic < wave_in_ch_val; wave_ic++) begin
                    automatic int ich_start, ich_end;
                    get_wave_range(in_ch, wave_in_ch_val, wave_ic, ich_start, ich_end);
                    if (ich_start >= ich_end) continue;

                    for (int och = och_start; och < och_end; och++) begin
                        for (int kh = 0; kh < kernel_size; kh++) begin
                            for (int kw = 0; kw < 3; kw++) begin
                                automatic logic [TDW-1:0] data_pkt = '0;
                                automatic logic [63:0] mask_val = '0;
                                for (int ich = 0; ich < 4; ich++) begin
                                    automatic int ich_global = ich_start + ich;
                                    if (ich_global >= in_ch || ich_global >= 4) continue;
                                    begin
                                        automatic int w_idx = idx4d(out_ch, kernel_size, 3, 4, och, kh, kw, ich_global);
                                        data_pkt[(ich*16) +: 16] = input_weight[w_idx];
                                        mask_val = mask_val | (64'd1 << ich);
                                    end
                                end
                                if (mask_val == 0) continue;
                                send_data_ps(kh[15:0], data_pkt, 1'b0, mask_val);
                            end
                        end
                    end
                end
            end
        end
    endtask

    task automatic distribute_conv2d_pd();
        automatic int wave_out_h_val  = (temporal_wave_out_h  > 1) ? temporal_wave_out_h  : 1;
        automatic int wave_out_ch_val = (temporal_wave_out_ch > 1) ? temporal_wave_out_ch : 1;
        automatic int wave_in_ch_val  = (temporal_wave_in_ch  > 1) ? temporal_wave_in_ch  : 1;
        automatic int loop_in_h  = ultra_mode_flag ? (in_height / NUM_PORTS) : in_height;
        automatic int loop_out_h = ultra_mode_flag ? (out_height / NUM_PORTS) : out_height;
        automatic int channels_per_pkt = ultra_mode_flag ? 4 : 12;
        $display("[TB-NoC-PD] Distributing Conv2D Activations...");

        for (int wave_h = 0; wave_h < wave_out_h_val; wave_h++) begin
            automatic int oh_start, oh_end, ih_start, ih_end_val;
            get_wave_range(loop_out_h, wave_out_h_val, wave_h, oh_start, oh_end);
            if (oh_start >= oh_end) continue;
            ih_start = oh_start * stride_val;
            ih_end_val = oh_end * stride_val + kernel_size - 1;
            if (ih_end_val > loop_in_h) ih_end_val = loop_in_h;

            for (int wave_oc = 0; wave_oc < wave_out_ch_val; wave_oc++) begin
                for (int wave_ic = 0; wave_ic < wave_in_ch_val; wave_ic++) begin
                    automatic int ich_start, ich_end;
                    get_wave_range(in_ch, wave_in_ch_val, wave_ic, ich_start, ich_end);
                    if (ich_start >= ich_end) continue;

                    for (int iw = 0; iw < in_width; iw++) begin
                        for (int ih = ih_start; ih < ih_end_val; ih++) begin
                            for (int ich_base = ich_start; ich_base < ich_end; ich_base += channels_per_pkt) begin
                                automatic logic [TDW-1:0] data_pkt = '0;
                                automatic logic [63:0] mask_val = '0;
                                automatic int current_chunk = channels_per_pkt;
                                if (ich_base + current_chunk > ich_end)
                                    current_chunk = ich_end - ich_base;

                                if (ultra_mode_flag) begin
                                    for (int ih_u = 0; ih_u < NUM_PORTS; ih_u++) begin
                                        for (int c_off = 0; c_off < current_chunk; c_off++) begin
                                            automatic int ich_val = ich_base + c_off;
                                            if (ich_val >= in_ch) continue;
                                            begin
                                                automatic int base_h = ih_u * loop_in_h + ih;
                                                automatic int a_idx = idx3d(in_height, in_width, in_ch, base_h, iw, ich_val);
                                                automatic int slot = ih_u * 4 + c_off;
                                                data_pkt[(slot*16) +: 16] = input_activation[a_idx];
                                                mask_val = mask_val | (64'd1 << slot);
                                            end
                                        end
                                    end
                                end else begin
                                    for (int c_off = 0; c_off < current_chunk; c_off++) begin
                                        automatic int ich_val = ich_base + c_off;
                                        if (ich_val >= in_ch) continue;
                                        begin
                                            automatic int a_idx = idx3d(in_height, in_width, in_ch, ih, iw, ich_val);
                                            data_pkt[(c_off*16) +: 16] = input_activation[a_idx];
                                            mask_val = mask_val | (64'd1 << c_off);
                                        end
                                    end
                                end

                                if (mask_val == 0) continue;
                                begin
                                    automatic logic [15:0] tag_val = (ih - ih_start);
                                    send_data_pd(tag_val, data_pkt, ultra_mode_flag, mask_val);
                                end
                            end
                        end
                    end
                end
            end
        end
    endtask

    task automatic distribute_conv2d_pli();
        automatic int wave_out_h_val  = (temporal_wave_out_h  > 1) ? temporal_wave_out_h  : 1;
        automatic int wave_out_ch_val = (temporal_wave_out_ch > 1) ? temporal_wave_out_ch : 1;
        automatic int wave_in_ch_val  = (temporal_wave_in_ch  > 1) ? temporal_wave_in_ch  : 1;
        automatic int loop_out_h = ultra_mode_flag ? (out_height / NUM_PORTS) : out_height;
        $display("[TB-NoC-PLI] Distributing Conv2D Partial Sums (Write)...");

        for (int wave_h = 0; wave_h < wave_out_h_val; wave_h++) begin
            automatic int oh_start, oh_end;
            get_wave_range(loop_out_h, wave_out_h_val, wave_h, oh_start, oh_end);
            if (oh_start >= oh_end) continue;

            for (int wave_oc = 0; wave_oc < wave_out_ch_val; wave_oc++) begin
                automatic int och_start, och_end;
                get_wave_range(out_ch, wave_out_ch_val, wave_oc, och_start, och_end);
                if (och_start >= och_end) continue;

                for (int wave_ic = 0; wave_ic < wave_in_ch_val; wave_ic++) begin
                    if (wave_ic != 0) continue; // Only seed on first in_ch wave

                    for (int ow = 0; ow < out_width; ow++) begin
                        for (int oh = oh_start; oh < oh_end; oh++) begin
                            for (int och = och_start; och < och_end; och += 4) begin
                                automatic logic [TDW-1:0] data_pkt = '0;
                                automatic logic [63:0] mask_val = '0;

                                if (ultra_mode_flag) begin
                                    for (int oh_u = 0; oh_u < NUM_PORTS; oh_u++) begin
                                        for (int och_off = 0; och_off < 4; och_off++) begin
                                            automatic int och_idx = och + och_off;
                                            if (och_idx >= out_ch || och_idx >= och_end) continue;
                                            begin
                                                automatic int base_h = oh_u * loop_out_h + oh;
                                                automatic int ps_i = idx3d(out_height, out_width, out_ch, base_h, ow, och_idx);
                                                automatic logic [15:0] ps_val = partial_sum_zero ? 16'h0 : input_partial_sum[ps_i];
                                                automatic int slot = oh_u * 4 + och_off;
                                                data_pkt[(slot*16) +: 16] = ps_val;
                                                mask_val = mask_val | (64'd1 << slot);
                                            end
                                        end
                                    end
                                end else begin
                                    for (int och_off = 0; och_off < 4; och_off++) begin
                                        automatic int och_idx = och + och_off;
                                        if (och_idx >= out_ch || och_idx >= och_end) continue;
                                        begin
                                            automatic int ps_i = idx3d(out_height, out_width, out_ch, oh, ow, och_idx);
                                            automatic logic [15:0] ps_val = partial_sum_zero ? 16'h0 : input_partial_sum[ps_i];
                                            data_pkt[(och_off*16) +: 16] = ps_val;
                                            mask_val = mask_val | (64'd1 << och_off);
                                        end
                                    end
                                end

                                if (mask_val == 0) continue;
                                begin
                                    automatic logic [15:0] tag_val = oh - oh_start;
                                    send_data_pli(tag_val, data_pkt, ultra_mode_flag, mask_val);
                                end
                            end
                        end
                    end
                end
            end
        end
    endtask

    task automatic distribute_conv2d_plo();
        automatic int wave_out_h_val  = (temporal_wave_out_h  > 1) ? temporal_wave_out_h  : 1;
        automatic int wave_out_ch_val = (temporal_wave_out_ch > 1) ? temporal_wave_out_ch : 1;
        automatic int wave_in_ch_val  = (temporal_wave_in_ch  > 1) ? temporal_wave_in_ch  : 1;
        automatic int loop_out_h = ultra_mode_flag ? (out_height / NUM_PORTS) : out_height;
        automatic longint unsigned plo_per_port_stride = loop_out_h * out_width * out_ch;
        $display("[TB-NoC-PLO] Distributing Conv2D Read Requests...");

        for (int wave_h = 0; wave_h < wave_out_h_val; wave_h++) begin
            automatic int oh_start, oh_end;
            get_wave_range(loop_out_h, wave_out_h_val, wave_h, oh_start, oh_end);
            if (oh_start >= oh_end) continue;

            for (int wave_oc = 0; wave_oc < wave_out_ch_val; wave_oc++) begin
                automatic int och_start, och_end;
                get_wave_range(out_ch, wave_out_ch_val, wave_oc, och_start, och_end);
                if (och_start >= och_end) continue;

                for (int wave_ic = 0; wave_ic < wave_in_ch_val; wave_ic++) begin
                    if (wave_ic != wave_in_ch_val - 1) continue; // Only read after final in_ch wave

                    for (int ow = 0; ow < out_width; ow++) begin
                        for (int oh = oh_start; oh < oh_end; oh++) begin
                            for (int och = och_start; och < och_end; och += 4) begin
                                if (och >= out_ch) continue;
                                begin
                                    automatic logic [15:0] tag_val = oh - oh_start;
                                    automatic longint unsigned base_i = idx3d(out_height, out_width, out_ch, oh, ow, och);
                                    recv_data_plo(tag_val, base_i, ultra_mode_flag,
                                                  ultra_mode_flag ? plo_per_port_stride : 0, NUM_PORTS);
                                end
                            end
                        end
                    end
                end
            end
        end
    endtask

    // =========================================================================
    // GEMM distribution tasks
    // =========================================================================
    task automatic distribute_gemm_ps();
        automatic int K_val = gemm_K, N_val = gemm_N;
        automatic int PE_N_val = pe_n, PE_K_val = pe_k;
        automatic int w_k, w_n;
        $display("[TB-NoC-PS] Distributing GEMM Weights...");

        w_k = (grid_k_per_wave_len == 0) ? ((wave_k > 1) ? wave_k : 1) : grid_k_per_wave_len;
        w_n = (grid_n_per_wave_len == 0) ? ((wave_n > 1) ? wave_n : 1) : grid_n_per_wave_len;

        for (int wave_k_idx = 0; wave_k_idx < w_k; wave_k_idx++) begin
            automatic int kt_start, kt_end, k_start_val, k_end_val;
            get_wave_tile_range(grid_k_per_wave, grid_k_per_wave_len, wave_k_idx, grid_k, w_k, kt_start, kt_end);
            k_start_val = kt_start * PE_K_val;
            k_end_val = kt_end * PE_K_val;
            if (k_end_val > K_val) k_end_val = K_val;
            if (k_start_val >= k_end_val) continue;

            for (int wave_n_idx = 0; wave_n_idx < w_n; wave_n_idx++) begin
                automatic int n_rng_start, n_rng_end, n_start_val, n_end_val;
                get_wave_tile_range(grid_n_per_wave, grid_n_per_wave_len, wave_n_idx, grid_n, w_n, n_rng_start, n_rng_end);
                n_start_val = n_rng_start * PE_N_val;
                n_end_val = n_rng_end * PE_N_val;
                if (n_end_val > N_val) n_end_val = N_val;
                if (n_start_val >= n_end_val) continue;

                if (gemm_ultra_mode) begin
                    for (int k_offset = 0; k_offset < PE_K_val; k_offset++) begin
                        for (int n_base = 0; n_base < N_val; n_base += 4) begin
                            automatic int n_end_local = n_base + 4;
                            automatic logic [TDW-1:0] data_pkt = '0;
                            automatic logic [63:0] mask_val = '0;
                            if (n_end_local > N_val) n_end_local = N_val;
                            if (n_end_local <= n_start_val || n_base >= n_end_val) continue;

                            for (int port = 0; port < NUM_PORTS; port++) begin
                                automatic int k_tile = kt_start + port;
                                if (k_tile >= kt_end) continue;
                                begin
                                    automatic int k_global = k_tile * PE_K_val + k_offset;
                                    if (k_global < k_start_val || k_global >= k_end_val) continue;
                                    for (int n_off = 0; n_off < 4; n_off++) begin
                                        automatic int n_val = n_base + n_off;
                                        if (n_val >= n_end_local || n_val < n_start_val || n_val >= n_end_val) continue;
                                        begin
                                            automatic int w_idx = idx2d(K_val, N_val, k_global, n_val);
                                            automatic int bit_off = port * 64 + n_off * 16;
                                            data_pkt[bit_off +: 16] = input_weight[w_idx];
                                            mask_val = mask_val | (64'd1 << n_off);
                                        end
                                    end
                                end
                            end
                            if (mask_val == 0) continue;
                            begin
                                automatic logic [15:0] tag_val = (n_base - n_start_val) / PE_N_val;
                                send_data_ps(tag_val, data_pkt, 1'b1, mask_val);
                            end
                        end
                    end
                end else begin
                    for (int k = k_start_val; k < k_end_val; k++) begin
                        for (int n_base = 0; n_base < N_val; n_base += 4) begin
                            automatic int n_end_local = n_base + 4;
                            automatic logic [TDW-1:0] data_pkt = '0;
                            automatic logic [63:0] mask_val = '0;
                            if (n_end_local > N_val) n_end_local = N_val;
                            if (n_end_local <= n_start_val || n_base >= n_end_val) continue;

                            for (int n_off = 0; n_off < 4; n_off++) begin
                                automatic int n_val = n_base + n_off;
                                if (n_val >= n_end_local || n_val < n_start_val || n_val >= n_end_val) continue;
                                begin
                                    automatic int w_idx = idx2d(K_val, N_val, k, n_val);
                                    data_pkt[(n_off*16) +: 16] = input_weight[w_idx];
                                    mask_val = mask_val | (64'd1 << n_off);
                                end
                            end
                            if (mask_val == 0) continue;
                            begin
                                automatic int n_idx_val = n_base / PE_N_val;
                                automatic int k_idx_val = k / PE_K_val;
                                automatic logic [15:0] tag_val = k_idx_val * grid_n + n_idx_val;
                                send_data_ps(tag_val, data_pkt, 1'b0, mask_val);
                            end
                        end
                    end
                end
            end
        end
        $display("[TB-NoC-PS] Weights Distribution Complete.");
    endtask

    task automatic distribute_gemm_pd();
        automatic int M_val = gemm_M, K_val = gemm_K;
        automatic int PE_M_val = pe_m, PE_K_val = pe_k;
        automatic int w_k, w_n, w_m;
        $display("[TB-NoC-PD] Distributing GEMM Activations...");

        w_k = (grid_k_per_wave_len == 0) ? ((wave_k > 1) ? wave_k : 1) : grid_k_per_wave_len;
        w_n = (grid_n_per_wave_len == 0) ? ((wave_n > 1) ? wave_n : 1) : grid_n_per_wave_len;
        w_m = (grid_m_per_wave_len == 0) ? ((wave_m > 1) ? wave_m : 1) : grid_m_per_wave_len;

        for (int wave_k_idx = 0; wave_k_idx < w_k; wave_k_idx++) begin
            automatic int kt_start, kt_end, k_start_val, k_end_val;
            get_wave_tile_range(grid_k_per_wave, grid_k_per_wave_len, wave_k_idx, grid_k, w_k, kt_start, kt_end);
            k_start_val = kt_start * PE_K_val;
            k_end_val = kt_end * PE_K_val;
            if (k_end_val > K_val) k_end_val = K_val;
            if (k_start_val >= k_end_val) continue;

            for (int wave_n_idx = 0; wave_n_idx < w_n; wave_n_idx++) begin
                automatic int n_rng_start, n_rng_end;
                automatic int n_tiles, max_m_tiles;
                get_wave_tile_range(grid_n_per_wave, grid_n_per_wave_len, wave_n_idx, grid_n, w_n, n_rng_start, n_rng_end);
                n_tiles = n_rng_end - n_rng_start;
                max_m_tiles = (gemm_ultra_mode && n_tiles > 0) ? (NUM_PES_PER_PORT / n_tiles) : 0;

                for (int wave_m_idx = 0; wave_m_idx < w_m; wave_m_idx++) begin
                    automatic int m_rng_start, m_rng_end, m_start_val, m_end_val;
                    get_wave_tile_range(grid_m_per_wave, grid_m_per_wave_len, wave_m_idx, grid_m, w_m, m_rng_start, m_rng_end);
                    m_start_val = m_rng_start * PE_M_val;
                    m_end_val = m_rng_end * PE_M_val;
                    if (m_end_val > M_val) m_end_val = M_val;
                    if (m_start_val >= m_end_val) continue;

                    for (int k_offset = 0; k_offset < PE_K_val; k_offset++) begin
                        if (gemm_ultra_mode) begin
                            for (int m_base = m_start_val; m_base < m_end_val; m_base += 4) begin
                                automatic logic [TDW-1:0] data_pkt = '0;
                                for (int port = 0; port < NUM_PORTS; port++) begin
                                    automatic int k_tile = kt_start + port;
                                    if (k_tile >= kt_end) continue;
                                    begin
                                        automatic int k_global = k_tile * PE_K_val + k_offset;
                                        if (k_global < k_start_val || k_global >= k_end_val) continue;
                                        for (int m_off = 0; m_off < 4; m_off++) begin
                                            automatic int m_val = m_base + m_off;
                                            if (m_val >= M_val) continue;
                                            begin
                                                automatic int a_idx = idx2d(M_val, K_val, m_val, k_global);
                                                automatic int bit_off = port * 64 + m_off * 16;
                                                data_pkt[bit_off +: 16] = input_activation[a_idx];
                                            end
                                        end
                                    end
                                end
                                begin
                                    automatic int m_idx_local = (m_base - m_start_val) / PE_M_val;
                                    automatic logic [15:0] tag_val = m_idx_local;
                                    send_data_pd(tag_val, data_pkt, 1'b1, 64'hF);
                                end
                            end
                        end else begin
                            for (int m_base = m_start_val; m_base < m_end_val; m_base += 4) begin
                                for (int k_tile = 0; k_tile < grid_k; k_tile++) begin
                                    automatic int k_global = k_tile * PE_K_val + k_offset;
                                    if (k_global >= K_val) continue;
                                    if (k_global < k_start_val || k_global >= k_end_val) continue;
                                    begin
                                        automatic logic [TDW-1:0] data_pkt = '0;
                                        for (int m_off = 0; m_off < 4; m_off++) begin
                                            automatic int m_val = m_base + m_off;
                                            if (m_val >= M_val) continue;
                                            begin
                                                automatic int a_idx = idx2d(M_val, K_val, m_val, k_global);
                                                data_pkt[(m_off*16) +: 16] = input_activation[a_idx];
                                            end
                                        end
                                        begin
                                            automatic int m_idx_val = m_base / PE_M_val;
                                            automatic logic [15:0] tag_val = k_tile * grid_m + m_idx_val;
                                            send_data_pd(tag_val, data_pkt, 1'b0, 64'hF);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        $display("[TB-NoC-PD] Activations Distribution Complete.");
    endtask

    task automatic distribute_gemm_pli();
        automatic int M_val = gemm_M, N_val = gemm_N;
        automatic int PE_M_val = pe_m, PE_N_val = pe_n;
        automatic int rows_per_port = gemm_ultra_mode ? (M_val / NUM_PORTS) : M_val;
        automatic int w_k, w_n, w_m;
        $display("[TB-NoC-PLI] Distributing GEMM Partial Sums (Write)...");

        w_k = (grid_k_per_wave_len == 0) ? ((wave_k > 1) ? wave_k : 1) : grid_k_per_wave_len;
        w_n = (grid_n_per_wave_len == 0) ? ((wave_n > 1) ? wave_n : 1) : grid_n_per_wave_len;
        w_m = (grid_m_per_wave_len == 0) ? ((wave_m > 1) ? wave_m : 1) : grid_m_per_wave_len;

        for (int wave_k_idx = 0; wave_k_idx < w_k; wave_k_idx++) begin
            if (wave_k_idx != 0) continue;

            for (int wave_n_idx = 0; wave_n_idx < w_n; wave_n_idx++) begin
                automatic int n_rng_start, n_rng_end, n_start_val, n_end_val;
                automatic int n_tiles, max_m_tiles;
                get_wave_tile_range(grid_n_per_wave, grid_n_per_wave_len, wave_n_idx, grid_n, w_n, n_rng_start, n_rng_end);
                n_start_val = n_rng_start * PE_N_val;
                n_end_val = n_rng_end * PE_N_val;
                if (n_end_val > N_val) n_end_val = N_val;
                if (n_start_val >= n_end_val) continue;
                n_tiles = n_rng_end - n_rng_start;
                max_m_tiles = (gemm_ultra_mode && n_tiles > 0) ? (NUM_PES_PER_PORT / n_tiles) : 0;

                for (int wave_m_idx = 0; wave_m_idx < w_m; wave_m_idx++) begin
                    automatic int m_rng_start, m_rng_end, m_start_val, m_end_val;
                    get_wave_tile_range(grid_m_per_wave, grid_m_per_wave_len, wave_m_idx, grid_m, w_m, m_rng_start, m_rng_end);
                    m_start_val = m_rng_start * PE_M_val;
                    m_end_val = m_rng_end * PE_M_val;
                    if (m_end_val > M_val) m_end_val = M_val;
                    if (m_start_val >= m_end_val) continue;

                    for (int n = n_start_val; n < n_end_val; n++) begin
                        if (gemm_ultra_mode && grid_k > 1) begin
                            // K-Split Ultra: send to Bus 0 only (mask 0x1)
                            for (int m = m_start_val; m < m_end_val; m += 4) begin
                                automatic logic [TDW-1:0] data_pkt = '0;
                                for (int m_off = 0; m_off < 4; m_off++) begin
                                    if (m + m_off >= M_val) continue;
                                    begin
                                        automatic int ps_i = idx2d(M_val, N_val, m + m_off, n);
                                        automatic logic [15:0] ps_val = gemm_partial_sum_zero ? 16'h0 : input_partial_sum[ps_i];
                                        data_pkt[(m_off*16) +: 16] = ps_val;
                                    end
                                end
                                begin
                                    automatic int m_idx_local = (m - m_start_val) / PE_M_val;
                                    automatic int n_idx_local = (n - n_start_val) / PE_N_val;
                                    automatic logic [15:0] tag_val = m_idx_local * n_tiles + n_idx_local;
                                    send_data_pli(tag_val, data_pkt, 1'b1, 64'h1);
                                end
                            end
                        end else if (gemm_ultra_mode) begin
                            // Ultra non-K-split: per-port PLI
                            for (int port = 0; port < NUM_PORTS; port++) begin
                                automatic int port_base = port * rows_per_port;
                                automatic int m_local_start, m_local_end;
                                if (port_base >= M_val) continue;
                                m_local_start = (m_start_val > port_base) ? (m_start_val - port_base) : 0;
                                m_local_end = (m_end_val > port_base) ? m_end_val - port_base : 0;
                                if (m_local_end > rows_per_port) m_local_end = rows_per_port;
                                if (m_local_start >= m_local_end) continue;
                                for (int m_local = m_local_start; m_local < m_local_end; m_local += 4) begin
                                    automatic logic [TDW-1:0] data_pkt = '0;
                                    for (int m_off = 0; m_off < 4; m_off++) begin
                                        automatic int m_global = port * rows_per_port + m_local + m_off;
                                        if (m_global >= M_val) continue;
                                        begin
                                            automatic int ps_i = idx2d(M_val, N_val, m_global, n);
                                            automatic logic [15:0] ps_val = gemm_partial_sum_zero ? 16'h0 : input_partial_sum[ps_i];
                                            data_pkt[(m_off*16) +: 16] = ps_val;
                                        end
                                    end
                                    begin
                                        automatic int m_idx_local = (m_local - m_local_start) / PE_M_val;
                                        automatic int n_idx_local = (n - n_start_val) / PE_N_val;
                                        automatic logic [15:0] tag_val = m_idx_local * n_tiles + n_idx_local;
                                        send_data_pli(tag_val, data_pkt, 1'b1, 64'hF);
                                    end
                                end
                            end
                        end else begin
                            // Normal mode
                            for (int m = m_start_val; m < m_end_val; m += 4) begin
                                automatic logic [TDW-1:0] data_pkt = '0;
                                for (int m_off = 0; m_off < 4; m_off++) begin
                                    if (m + m_off >= M_val) continue;
                                    begin
                                        automatic int ps_i = idx2d(M_val, N_val, m + m_off, n);
                                        automatic logic [15:0] ps_val = gemm_partial_sum_zero ? 16'h0 : input_partial_sum[ps_i];
                                        data_pkt[(m_off*16) +: 16] = ps_val;
                                    end
                                end
                                begin
                                    automatic int m_idx_val = m / PE_M_val;
                                    automatic int n_idx_val = n / PE_N_val;
                                    automatic logic [15:0] tag_val = m_idx_val * grid_n + n_idx_val;
                                    send_data_pli(tag_val, data_pkt, 1'b0, 64'hF);
                                end
                            end
                        end
                    end
                end
            end
        end
    endtask

    task automatic distribute_gemm_plo();
        automatic int M_val = gemm_M, N_val = gemm_N;
        automatic int PE_M_val = pe_m, PE_N_val = pe_n;
        automatic int rows_per_port = gemm_ultra_mode ? (M_val / NUM_PORTS) : M_val;
        automatic longint unsigned per_port_stride = gemm_ultra_mode ? (rows_per_port * N_val) : 0;
        automatic int w_k, w_n, w_m;
        $display("[TB-NoC-PLO] Distributing GEMM Read Requests...");

        w_k = (grid_k_per_wave_len == 0) ? ((wave_k > 1) ? wave_k : 1) : grid_k_per_wave_len;
        w_n = (grid_n_per_wave_len == 0) ? ((wave_n > 1) ? wave_n : 1) : grid_n_per_wave_len;
        w_m = (grid_m_per_wave_len == 0) ? ((wave_m > 1) ? wave_m : 1) : grid_m_per_wave_len;

        for (int wave_k_idx = 0; wave_k_idx < w_k; wave_k_idx++) begin
            if (wave_k_idx != (w_k - 1)) continue; // Only read on last k-wave

            for (int wave_n_idx = 0; wave_n_idx < w_n; wave_n_idx++) begin
                automatic int n_rng_start, n_rng_end, n_start_val, n_end_val;
                automatic int n_tiles, max_m_tiles;
                get_wave_tile_range(grid_n_per_wave, grid_n_per_wave_len, wave_n_idx, grid_n, w_n, n_rng_start, n_rng_end);
                n_start_val = n_rng_start * PE_N_val;
                n_end_val = n_rng_end * PE_N_val;
                if (n_end_val > N_val) n_end_val = N_val;
                if (n_start_val >= n_end_val) continue;
                n_tiles = n_rng_end - n_rng_start;
                max_m_tiles = (gemm_ultra_mode && n_tiles > 0) ? (NUM_PES_PER_PORT / n_tiles) : 0;

                for (int wave_m_idx = 0; wave_m_idx < w_m; wave_m_idx++) begin
                    automatic int m_rng_start, m_rng_end, m_start_val, m_end_val;
                    get_wave_tile_range(grid_m_per_wave, grid_m_per_wave_len, wave_m_idx, grid_m, w_m, m_rng_start, m_rng_end);
                    m_start_val = m_rng_start * PE_M_val;
                    m_end_val = m_rng_end * PE_M_val;
                    if (m_end_val > M_val) m_end_val = M_val;
                    if (m_start_val >= m_end_val) continue;

                    for (int n = n_start_val; n < n_end_val; n++) begin
                        if (gemm_ultra_mode && grid_k > 1) begin
                            // K-Split Ultra: read from Bus 2 (normal packet)
                            for (int m = m_start_val; m < m_end_val; m += 4) begin
                                automatic int m_idx_local = (m - m_start_val) / PE_M_val;
                                automatic int n_idx_local = (n - n_start_val) / PE_N_val;
                                automatic logic [15:0] tag_val = m_idx_local * n_tiles + n_idx_local;
                                automatic longint unsigned base_i = idx2d(M_val, N_val, m, n);
                                recv_data_plo(tag_val, base_i, 1'b0, 0, NUM_PORTS);
                            end
                        end else if (gemm_ultra_mode && grid_k == 1) begin
                            // Ultra non-K-split: per-port requests
                            for (int port = 0; port < NUM_PORTS; port++) begin
                                automatic int port_base = port * rows_per_port;
                                automatic int m_local_start, m_local_end;
                                if (port_base >= M_val) continue;
                                m_local_start = (m_start_val > port_base) ? (m_start_val - port_base) : 0;
                                m_local_end = (m_end_val > port_base) ? m_end_val - port_base : 0;
                                if (m_local_end > rows_per_port) m_local_end = rows_per_port;
                                if (m_local_start >= m_local_end) continue;
                                for (int m_local = m_local_start; m_local < m_local_end; m_local += 4) begin
                                    automatic int m_idx_local = (m_local - m_local_start) / PE_M_val;
                                    automatic int n_idx_local = (n - n_start_val) / PE_N_val;
                                    automatic logic [15:0] tag_val = n_idx_local;
                                    automatic int m_global = port_base + m_local;
                                    automatic longint unsigned base_i = idx2d(M_val, N_val, m_global, n);
                                    recv_data_plo(tag_val, base_i, 1'b1, per_port_stride, NUM_PORTS);
                                end
                            end
                        end else begin
                            // Normal mode
                            for (int m = m_start_val; m < m_end_val; m += 4) begin
                                automatic int m_idx_local = (m - m_start_val) / PE_M_val;
                                automatic int n_idx_local = (n - n_start_val) / PE_N_val;
                                automatic logic [15:0] tag_val = m_idx_local * n_tiles + n_idx_local;
                                automatic longint unsigned base_i = idx2d(M_val, N_val, m, n);
                                recv_data_plo(tag_val, base_i, 1'b0, 0, NUM_PORTS);
                            end
                        end
                    end
                end
            end
        end
    endtask

    // =========================================================================
    // PS sender (scan chain → program → start PE → data)
    // =========================================================================
    initial begin : ps_sender_proc
        @(data_loaded_ev);

        // Step 1: configure scan chain
        configure_scan_chain();
        -> scan_chain_done_ev;

        // Step 2: load PE program
        load_pe_program_task();
        -> program_done_ev;

        // Step 3: start PEs
        $display("[TB] Starting PEs...");
        send_command(CMD_START_PE);
        -> pe_start_done_ev;

        // Step 4: stream PS data
        @(start_traffic_ev);
        if (mode_str == "conv2d")
            distribute_conv2d_ps();
        else if (mode_str == "gemm")
            distribute_gemm_ps();
        ps_finished = 1;
        -> ps_done_ev;
    end

    // =========================================================================
    // PD sender
    // =========================================================================
    initial begin : pd_sender_proc
        @(start_traffic_ev);
        if (mode_str == "conv2d")
            distribute_conv2d_pd();
        else if (mode_str == "gemm")
            distribute_gemm_pd();
        pd_finished = 1;
        -> pd_done_ev;
    end

    // =========================================================================
    // PLI sender
    // =========================================================================
    initial begin : pli_sender_proc
        @(start_traffic_ev);
        if (mode_str == "conv2d")
            distribute_conv2d_pli();
        else if (mode_str == "gemm")
            distribute_gemm_pli();
        pli_finished = 1;
        -> pli_done_ev;
    end

    // =========================================================================
    // PLO sender
    // =========================================================================
    initial begin : plo_sender_proc
        @(start_traffic_ev);
        if (mode_str == "conv2d")
            distribute_conv2d_plo();
        else if (mode_str == "gemm")
            distribute_gemm_plo();
        plo_finished = 1;
        -> plo_done_ev;
    end

    // =========================================================================
    // Verification: check_results (cosine similarity, MSE)
    // =========================================================================
    task automatic check_results();
        automatic int errors = 0;
        automatic real dot_product = 0.0;
        automatic real mag_received = 0.0;
        automatic real mag_expected = 0.0;
        automatic real max_diff = 0.0;
        automatic real total_se = 0.0;
        automatic int total_elem = expected_output.size();

        for (int i = 0; i < total_elem; i++) begin
            automatic real recv_val = fp16_to_real(output_partial_sum[i]);
            automatic real exp_val  = fp16_to_real(expected_output[i]);
            automatic real diff_val;

            dot_product  += recv_val * exp_val;
            mag_received += recv_val * recv_val;
            mag_expected += exp_val  * exp_val;

            diff_val = (recv_val > exp_val) ? (recv_val - exp_val) : (exp_val - recv_val);
            total_se += diff_val * diff_val;
            if (diff_val > max_diff) max_diff = diff_val;

            if (diff_val > verify_tolerance) begin
                errors++;
                if (errors <= 100) begin
                    $display("Mismatch at index %0d: received=0x%04h expected=0x%04h diff=%e",
                             i, output_partial_sum[i], expected_output[i], diff_val);
                end
            end
        end

        begin
            automatic real cosine_sim, mse_val;
            mag_received = $sqrt(mag_received);
            mag_expected = $sqrt(mag_expected);
            cosine_sim = (mag_received * mag_expected > 0) ?
                         (dot_product / (mag_received * mag_expected)) : 0.0;
            mse_val = (total_elem > 0) ? (total_se / total_elem) : 0.0;

            $display("----------------------------------------");
            $display("Verification Results:");
            $display("  Total Elements   : %0d", total_elem);
            $display("  Mismatches       : %0d (Tolerance: %e)", errors, verify_tolerance);
            $display("  Cosine Similarity: %f", cosine_sim);
            $display("  Max Difference   : %e", max_diff);
            $display("  MSE              : %e", mse_val);
            $display("----------------------------------------");

            if (cosine_sim > 0.99)
                $display("PASS: Outputs are highly similar! Test PASSED.");
            else
                $display("FAIL: Outputs are not similar enough. Test FAILED.");
        end
    endtask

    // =========================================================================
    // Statistics
    // =========================================================================
    function automatic string format_si(real value, string unit);
        if (value >= 1.0e12)
            return $sformatf("%.2f T%s", value / 1.0e12, unit);
        else if (value >= 1.0e9)
            return $sformatf("%.2f G%s", value / 1.0e9, unit);
        else if (value >= 1.0e6)
            return $sformatf("%.2f M%s", value / 1.0e6, unit);
        else if (value >= 1.0e3)
            return $sformatf("%.2f K%s", value / 1.0e3, unit);
        else
            return $sformatf("%.2f %s", value, unit);
    endfunction

    task automatic print_statistics();
        automatic real total_time_sec = $realtime / 1.0e9; // ns → s
        automatic real throughput_val, macs_per_sec, arith_intensity;
        $display("========================================");
        $display("              Statistics                ");
        $display("========================================");
        $display("Total NoC cycle count: %0d", $time / clk_rst.clock_period_ns);
        $display("Total NoC data movement: %s", format_si($itor(total_sent_bytes + total_received_bytes), "B"));
        if (total_time_sec > 0) begin
            throughput_val = $itor(total_sent_bytes + total_received_bytes) / total_time_sec;
            macs_per_sec   = $itor(total_macs) / total_time_sec;
            arith_intensity = (total_sent_bytes + total_received_bytes > 0) ?
                              $itor(total_macs) / $itor(total_sent_bytes + total_received_bytes) : 0.0;
            $display("NoC Throughput: %s/s", format_si(throughput_val, "B"));
            $display("Performance: %s/s (%s FLOPS)", format_si(macs_per_sec, "MACs"), format_si(macs_per_sec * 2, ""));
            $display("Arithmetic Intensity: %.2f MACs/Byte", arith_intensity);
        end
        $display("========================================");
    endtask

    // =========================================================================
    // Main test sequence
    // =========================================================================
    initial begin : test_main
        string data_dir;
        real tol_tmp;
        int  verbose_tmp;

        // Defaults
        command_mode    = 1'b0;
        command_data    = 32'h0;
        noc_ps_in_data  = '0; noc_ps_in_addr = '0; noc_ps_in_mask = '0; noc_ps_in_valid = 1'b0;
        noc_pd_in_data  = '0; noc_pd_in_addr = '0; noc_pd_in_mask = '0; noc_pd_in_valid = 1'b0;
        noc_pli_in_data = '0; noc_pli_in_addr= '0; noc_pli_in_mask= '0; noc_pli_in_valid= 1'b0;
        noc_plo_in_data = '0; noc_plo_in_valid = 1'b0;
        noc_plo_out_ready = 1'b0;
        total_sent_bytes = 0;
        total_received_bytes = 0;
        total_macs = 0;

        // Parse plusargs
        if (!$value$plusargs("DATA_DIR=%s", data_dir))
            data_dir = "../../output/noc-sim/conv_k3c4";
        if ($value$plusargs("VERIFY_TOL=%f", tol_tmp))
            verify_tolerance = tol_tmp;
        if ($value$plusargs("VERBOSE=%d", verbose_tmp))
            verbose = verbose_tmp;
        begin
            int interval_tmp, timeout_tmp;
            if ($value$plusargs("PROGRESS_INTERVAL=%d", interval_tmp) && interval_tmp > 0)
                progress_interval = interval_tmp;
            if ($value$plusargs("IDLE_TIMEOUT=%d", timeout_tmp) && timeout_tmp > 0)
                idle_timeout_cycles = timeout_tmp;
        end

        // 1. Wait for reset release
        @(posedge reset_n);
        @(posedge clk);

        // 2. Load test data
        load_test_data(data_dir);

        // 2b. Signal that test data is loaded
        -> data_loaded_ev;

        // 3. Parse config
        mode_str = cfg_get_str("mode", "conv2d");
        $display("[TB] Mode: %s", mode_str);

        if (mode_str == "conv2d") begin
            parse_conv_params();
            if (kernel_size <= 0 || in_ch <= 0 || out_ch <= 0 ||
                in_height <= 0 || in_width <= 0 || out_height <= 0 || out_width <= 0) begin
                $error("[TB] Invalid conv2d config!");
                $finish;
            end
        end else if (mode_str == "gemm") begin
            parse_gemm_params();
            if (gemm_M <= 0 || gemm_K <= 0 || gemm_N <= 0) begin
                $error("[TB] Invalid gemm config!");
                $finish;
            end
        end else begin
            $error("[TB] Unknown mode: %s", mode_str);
            $finish;
        end

        // 4. Wait for scan chain / program / PE start (driven by ps_sender)
        @(scan_chain_done_ev);
        $display("[TB] Scan Chain configured.");

        @(program_done_ev);
        $display("[TB] PE Program loaded.");

        @(pe_start_done_ev);
        $display("[TB] PEs started.");

        // 5. Calculate MACs
        if (mode_str == "conv2d") begin
            total_macs = out_ch * out_height * out_width * kernel_size * kernel_size * in_ch;
        end else if (mode_str == "gemm") begin
            total_macs = gemm_M * gemm_N * gemm_K;
        end

        // 6. Start parallel data distribution
        $display("[TB] Starting Parallel Data Distribution...");
        -> start_traffic_ev;

        // 7. Wait for all senders to finish
        $display("[TB] Running Simulation...");
        fork
            @(ps_done_ev);
            @(pd_done_ev);
            @(pli_done_ev);
            @(plo_done_ev);
        join

        $display("[TB] All senders done. meta_fifo remaining=%0d", meta_fifo_available());

        // 8. Wait for remaining responses to drain
        begin
            automatic int drain_waited = 0;
            while (meta_fifo_available() > 0 && drain_waited < MAX_WAIT_CYCLES) begin
                @(posedge clk);
                drain_waited++;
            end
            if (meta_fifo_available() > 0) begin
                $error("[TB] Timeout waiting for responses to drain (remaining=%0d)", meta_fifo_available());
                $finish;
            end
        end

        // 9. Check results
        $display("[TB] Checking Results...");
        check_results();

        // 10. Statistics
        print_statistics();

        // 11. Done
        $display("[TB] Simulation Finished.");
        $finish;
    end

    // =========================================================================
    // Idle timeout watchdog
    // =========================================================================
    initial begin : idle_timeout_watchdog
        automatic int timeout_val = 0;
        automatic int unsigned idle_count = 0;
        if ($value$plusargs("IDLE_TIMEOUT=%d", timeout_val) && timeout_val > 0) begin
            @(start_traffic_ev);
            forever begin
                @(posedge clk);
                if ((noc_ps_in_valid  && noc_ps_in_ready)  ||
                    (noc_pd_in_valid  && noc_pd_in_ready)  ||
                    (noc_pli_in_valid && noc_pli_in_ready)  ||
                    (noc_plo_in_valid && noc_plo_in_ready)  ||
                    (noc_plo_out_valid && noc_plo_out_ready)) begin
                    idle_count = 0;
                end else begin
                    idle_count++;
                end
                if (idle_count >= timeout_val) begin
                    $error("[TB] Idle timeout! No data transfer for %0d cycles.", timeout_val);
                    $display("[TB] Progress at timeout:");
                    $display("  PS  sent : %0d pkts", ps_pkt_count);
                    $display("  PD  sent : %0d pkts", pd_pkt_count);
                    $display("  PLI sent : %0d pkts", pli_pkt_count);
                    $display("  PLO req  : %0d pkts", plo_req_count);
                    $display("  PLO resp : %0d pkts", plo_resp_count);
                    $display("  Total TX : %0d bytes | Total RX : %0d bytes",
                             total_sent_bytes, total_received_bytes);
                    $finish;
                end
            end
        end
    end

    // =========================================================================
    // Simulation timeout guard
    // =========================================================================
    initial begin
        #500ms;
        $error("[TB] Global simulation timeout!");
        $finish;
    end

    // =========================================================================
    // print progress periodically
    // =========================================================================
    initial begin
        automatic int interval_val = 10000;
        if ($value$plusargs("PROGRESS_INTERVAL=%d", interval_val) && interval_val > 0) begin
            forever begin
                #interval_val;
                $display("[TB Progress] Time: %0t | PS sent: %0d pkts | PD sent: %0d pkts | PLI sent: %0d pkts | PLO req: %0d pkts | PLO resp: %0d pkts | Total TX: %0d bytes | Total RX: %0d bytes",
                         $time, ps_pkt_count, pd_pkt_count, pli_pkt_count, plo_req_count, plo_resp_count,
                         total_sent_bytes, total_received_bytes);
            end
        end
    end

endmodule
