#pragma once

#ifndef HACC_CORE_REGS_H_
#define HACC_CORE_REGS_H_

#include <stdint.h>

#define HACC_BIT32(bit) (UINT32_C(1) << (bit))

/* Core-visible address map */
#define HACC_CORE_ADDR_INST_RAM_BASE            UINT32_C(0x00000000)
#define HACC_CORE_ADDR_INST_RAM_SIZE            UINT32_C(0x00004000)

#define HACC_CORE_ADDR_BOOT_ROM_BASE            UINT32_C(0x00010000)
#define HACC_CORE_ADDR_BOOT_ROM_SIZE            UINT32_C(0x00001000)

#define HACC_CORE_ADDR_DATA_RAM_BASE            UINT32_C(0x10000000)
#define HACC_CORE_ADDR_DATA_RAM_SIZE            UINT32_C(0x00010000)

#define HACC_CORE_ADDR_LOCAL_CTRL_BASE          UINT32_C(0x20000000)
#define HACC_CORE_ADDR_LOCAL_CTRL_SIZE          UINT32_C(0x00001000)

#define HACC_CORE_ADDR_DMA_MMIO_BASE            UINT32_C(0x20001000)
#define HACC_CORE_ADDR_DMA_MMIO_SIZE            UINT32_C(0x00000800)

#define HACC_CORE_ADDR_DMA_RSVD_BASE            UINT32_C(0x20001800)
#define HACC_CORE_ADDR_DMA_RSVD_SIZE            UINT32_C(0x00000800)

#define HACC_CORE_ADDR_LOCAL_TIMER_BASE         UINT32_C(0x20002000)
#define HACC_CORE_ADDR_LOCAL_TIMER_SIZE         UINT32_C(0x00000100)

#define HACC_CORE_ADDR_PLIC_BASE                UINT32_C(0x0C000000)
#define HACC_CORE_ADDR_PLIC_SIZE                UINT32_C(0x00010000)

#define HACC_CORE_ADDR_CLUSTER_UNICAST_BASE     UINT32_C(0x40000000)
#define HACC_CORE_ADDR_CLUSTER_UNICAST_SIZE     UINT32_C(0x00100000)
#define HACC_CORE_ADDR_CLUSTER_UNICAST_STRIDE   UINT32_C(0x00010000)

#define HACC_CORE_ADDR_CLUSTER_BCAST_BASE       UINT32_C(0x50000000)
#define HACC_CORE_ADDR_CLUSTER_BCAST_SIZE       UINT32_C(0x00010000)

#define HACC_CORE_ADDR_NLU_BASE                 UINT32_C(0x60000000)
#define HACC_CORE_ADDR_NLU_SIZE                 UINT32_C(0x00010000)
#define HACC_CORE_ADDR_NLU_STRIDE               UINT32_C(0x00001000)

/* NLU internal register offsets are intentionally not defined here.
 * Core.md only architects the window base/stride plus the minimum register contract names.
 */

static inline uint32_t hacc_core_cluster_base(uint32_t cluster_id) {
	return HACC_CORE_ADDR_CLUSTER_UNICAST_BASE + (cluster_id * HACC_CORE_ADDR_CLUSTER_UNICAST_STRIDE);
}

static inline uint32_t hacc_core_cluster_bcast_addr(uint32_t cluster_local_offset) {
	return HACC_CORE_ADDR_CLUSTER_BCAST_BASE + cluster_local_offset;
}

static inline uint32_t hacc_core_nlu_base(uint32_t nlu_id) {
	return HACC_CORE_ADDR_NLU_BASE + (nlu_id * HACC_CORE_ADDR_NLU_STRIDE);
}

/* Cluster-local architected windows */
#define HACC_CLUSTER_LOCAL_SPM_CFG_BASE         UINT32_C(0x0000)
#define HACC_CLUSTER_LOCAL_SPM_CFG_END          UINT32_C(0x00FF)
#define HACC_CLUSTER_LOCAL_HDDU_BASE            UINT32_C(0x1000)
#define HACC_CLUSTER_LOCAL_HDDU_END             UINT32_C(0x1FFF)
#define HACC_CLUSTER_LOCAL_NOC_BASE             UINT32_C(0x2000)
#define HACC_CLUSTER_LOCAL_NOC_END              UINT32_C(0x20FF)

/* Host-visible CSR offsets on s_ctrl_axi_* */
#define HACC_HOST_REG_HACC_CAP0                 UINT32_C(0x0000)
#define HACC_HOST_REG_HACC_CAP1                 UINT32_C(0x0004)
#define HACC_HOST_REG_HACC_CTRL                 UINT32_C(0x0008)
#define HACC_HOST_REG_HACC_STATUS               UINT32_C(0x000C)
#define HACC_HOST_REG_CORE_BOOT_ADDR            UINT32_C(0x0010)
#define HACC_HOST_REG_CORE_TRAP_VECTOR          UINT32_C(0x0014)
#define HACC_HOST_REG_CORE_PC_SNAPSHOT          UINT32_C(0x0018)
#define HACC_HOST_REG_CORE_CAUSE_SNAPSHOT       UINT32_C(0x001C)
#define HACC_HOST_REG_MANIFEST_ADDR_LO          UINT32_C(0x0020)
#define HACC_HOST_REG_MANIFEST_ADDR_HI          UINT32_C(0x0024)
#define HACC_HOST_REG_MANIFEST_SIZE             UINT32_C(0x0028)
#define HACC_HOST_REG_MANIFEST_KICK             UINT32_C(0x002C)
#define HACC_HOST_REG_LOADER_STATUS             UINT32_C(0x0030)
#define HACC_HOST_REG_LOADER_ERR_CODE           UINT32_C(0x0034)
#define HACC_HOST_REG_LOADER_ERR_INFO           UINT32_C(0x0038)
#define HACC_HOST_REG_IRQ_SUMMARY               UINT32_C(0x0040)
#define HACC_HOST_REG_IRQ_FORCE_ACK             UINT32_C(0x0044)
#define HACC_HOST_REG_CLUSTER_MASK_LO           UINT32_C(0x0050)
#define HACC_HOST_REG_CLUSTER_MASK_HI           UINT32_C(0x0054)
#define HACC_HOST_REG_LAST_MMIO_TARGET          UINT32_C(0x0058)
#define HACC_HOST_REG_LAST_MMIO_ADDR            UINT32_C(0x005C)
#define HACC_HOST_REG_TRACE_BASE                UINT32_C(0x0060)
#define HACC_HOST_REG_TRACE_SIZE                UINT32_C(0x0064)
#define HACC_HOST_REG_TRACE_CTRL                UINT32_C(0x0068)
#define HACC_HOST_REG_TRACE_STATUS              UINT32_C(0x006C)

/* HACC_CTRL bits */
#define HACC_HOST_HACC_CTRL_CORE_EN_SHIFT       0u
#define HACC_HOST_HACC_CTRL_CORE_HALTREQ_SHIFT  1u
#define HACC_HOST_HACC_CTRL_CORE_RESUME_SHIFT   2u
#define HACC_HOST_HACC_CTRL_SW_RESET_SHIFT      3u
#define HACC_HOST_HACC_CTRL_LOADER_ABORT_SHIFT  4u
#define HACC_HOST_HACC_CTRL_AUTO_BOOT_SHIFT     5u

#define HACC_HOST_HACC_CTRL_CORE_EN_MASK        HACC_BIT32(HACC_HOST_HACC_CTRL_CORE_EN_SHIFT)
#define HACC_HOST_HACC_CTRL_CORE_HALTREQ_MASK   HACC_BIT32(HACC_HOST_HACC_CTRL_CORE_HALTREQ_SHIFT)
#define HACC_HOST_HACC_CTRL_CORE_RESUME_MASK    HACC_BIT32(HACC_HOST_HACC_CTRL_CORE_RESUME_SHIFT)
#define HACC_HOST_HACC_CTRL_SW_RESET_MASK       HACC_BIT32(HACC_HOST_HACC_CTRL_SW_RESET_SHIFT)
#define HACC_HOST_HACC_CTRL_LOADER_ABORT_MASK   HACC_BIT32(HACC_HOST_HACC_CTRL_LOADER_ABORT_SHIFT)
#define HACC_HOST_HACC_CTRL_AUTO_BOOT_MASK      HACC_BIT32(HACC_HOST_HACC_CTRL_AUTO_BOOT_SHIFT)

/* HACC_STATUS bits */
#define HACC_HOST_HACC_STATUS_LOADER_BUSY_SHIFT 0u
#define HACC_HOST_HACC_STATUS_LOADER_DONE_SHIFT 1u
#define HACC_HOST_HACC_STATUS_CORE_HALTED_SHIFT 2u
#define HACC_HOST_HACC_STATUS_CORE_RUNNING_SHIFT 3u
#define HACC_HOST_HACC_STATUS_FAULTED_SHIFT     4u
#define HACC_HOST_HACC_STATUS_LOAD_PHASE_SHIFT  5u
#define HACC_HOST_HACC_STATUS_MEM_AXI_OWNER_SHIFT 6u

#define HACC_HOST_HACC_STATUS_LOADER_BUSY_MASK  HACC_BIT32(HACC_HOST_HACC_STATUS_LOADER_BUSY_SHIFT)
#define HACC_HOST_HACC_STATUS_LOADER_DONE_MASK  HACC_BIT32(HACC_HOST_HACC_STATUS_LOADER_DONE_SHIFT)
#define HACC_HOST_HACC_STATUS_CORE_HALTED_MASK  HACC_BIT32(HACC_HOST_HACC_STATUS_CORE_HALTED_SHIFT)
#define HACC_HOST_HACC_STATUS_CORE_RUNNING_MASK HACC_BIT32(HACC_HOST_HACC_STATUS_CORE_RUNNING_SHIFT)
#define HACC_HOST_HACC_STATUS_FAULTED_MASK      HACC_BIT32(HACC_HOST_HACC_STATUS_FAULTED_SHIFT)
#define HACC_HOST_HACC_STATUS_LOAD_PHASE_MASK   HACC_BIT32(HACC_HOST_HACC_STATUS_LOAD_PHASE_SHIFT)
#define HACC_HOST_HACC_STATUS_MEM_AXI_OWNER_MASK HACC_BIT32(HACC_HOST_HACC_STATUS_MEM_AXI_OWNER_SHIFT)

/* IRQ_SUMMARY bits */
#define HACC_HOST_IRQ_SUMMARY_LOADER_DONE_SHIFT 0u
#define HACC_HOST_IRQ_SUMMARY_LOADER_ERR_SHIFT  1u
#define HACC_HOST_IRQ_SUMMARY_CORE_FAULT_SHIFT  2u
#define HACC_HOST_IRQ_SUMMARY_CORE_HALTED_SHIFT 3u
#define HACC_HOST_IRQ_SUMMARY_PLIC_PENDING_SHIFT 4u
#define HACC_HOST_IRQ_SUMMARY_TRACE_WM_SHIFT    5u

#define HACC_HOST_IRQ_SUMMARY_LOADER_DONE_MASK  HACC_BIT32(HACC_HOST_IRQ_SUMMARY_LOADER_DONE_SHIFT)
#define HACC_HOST_IRQ_SUMMARY_LOADER_ERR_MASK   HACC_BIT32(HACC_HOST_IRQ_SUMMARY_LOADER_ERR_SHIFT)
#define HACC_HOST_IRQ_SUMMARY_CORE_FAULT_MASK   HACC_BIT32(HACC_HOST_IRQ_SUMMARY_CORE_FAULT_SHIFT)
#define HACC_HOST_IRQ_SUMMARY_CORE_HALTED_MASK  HACC_BIT32(HACC_HOST_IRQ_SUMMARY_CORE_HALTED_SHIFT)
#define HACC_HOST_IRQ_SUMMARY_PLIC_PENDING_MASK HACC_BIT32(HACC_HOST_IRQ_SUMMARY_PLIC_PENDING_SHIFT)
#define HACC_HOST_IRQ_SUMMARY_TRACE_WM_MASK     HACC_BIT32(HACC_HOST_IRQ_SUMMARY_TRACE_WM_SHIFT)

/* LOADER_STATUS fields */
#define HACC_HOST_LOADER_STATUS_BUSY_SHIFT      0u
#define HACC_HOST_LOADER_STATUS_DONE_SHIFT      1u
#define HACC_HOST_LOADER_STATUS_ERR_SHIFT       2u
#define HACC_HOST_LOADER_STATUS_STATE_SHIFT     4u
#define HACC_HOST_LOADER_STATUS_STATE_MASK      UINT32_C(0x000000F0)
#define HACC_HOST_LOADER_STATUS_ENTRY_IDX_SHIFT 16u
#define HACC_HOST_LOADER_STATUS_ENTRY_IDX_MASK  UINT32_C(0xFFFF0000)

/* Loader FSM states */
#define HACC_LOADER_STATE_IDLE                  UINT32_C(0)
#define HACC_LOADER_STATE_FETCH                 UINT32_C(1)
#define HACC_LOADER_STATE_ROUTE                 UINT32_C(2)
#define HACC_LOADER_STATE_WRITE_LOCAL           UINT32_C(3)
#define HACC_LOADER_STATE_VERIFY                UINT32_C(4)
#define HACC_LOADER_STATE_DONE                  UINT32_C(5)
#define HACC_LOADER_STATE_ERR                   UINT32_C(6)

/* Loader error codes */
#define HACC_LOADER_ERR_NONE                    UINT32_C(0)
#define HACC_LOADER_ERR_MANIFEST_ALIGN          UINT32_C(1)
#define HACC_LOADER_ERR_BAD_SECTION_KIND        UINT32_C(2)
#define HACC_LOADER_ERR_LOCAL_ADDR_OOB          UINT32_C(3)
#define HACC_LOADER_ERR_SIZE_OOB                UINT32_C(4)
#define HACC_LOADER_ERR_CRC_MISMATCH            UINT32_C(5)
#define HACC_LOADER_ERR_AXI                     UINT32_C(6)
#define HACC_LOADER_ERR_OVERLAP                 UINT32_C(7)

/* Core-local control MMIO offsets */
#define HACC_LOCAL_REG_CLUSTER_MASK_LO          UINT32_C(0x000)
#define HACC_LOCAL_REG_CLUSTER_MASK_HI          UINT32_C(0x004)
#define HACC_LOCAL_REG_MMIO_ERR_STATUS          UINT32_C(0x008)
#define HACC_LOCAL_REG_LAST_TARGET_ID           UINT32_C(0x00C)
#define HACC_LOCAL_REG_LAST_FAULT_ADDR          UINT32_C(0x010)
#define HACC_LOCAL_REG_LAST_FAULT_INFO          UINT32_C(0x014)
#define HACC_LOCAL_REG_BOOT_REASON              UINT32_C(0x018)
#define HACC_LOCAL_REG_FABRIC_CAP0              UINT32_C(0x01C)

/* MMIO_ERR_STATUS bits */
#define HACC_LOCAL_MMIO_ERR_PENDING_SHIFT       0u
#define HACC_LOCAL_MMIO_ERR_DECODE_FAULT_SHIFT  1u
#define HACC_LOCAL_MMIO_ERR_BCAST_READ_SHIFT    2u
#define HACC_LOCAL_MMIO_ERR_TARGET_BUS_SHIFT    3u
#define HACC_LOCAL_MMIO_ERR_TIMEOUT_SHIFT       4u

#define HACC_LOCAL_MMIO_ERR_PENDING_MASK        HACC_BIT32(HACC_LOCAL_MMIO_ERR_PENDING_SHIFT)
#define HACC_LOCAL_MMIO_ERR_DECODE_FAULT_MASK   HACC_BIT32(HACC_LOCAL_MMIO_ERR_DECODE_FAULT_SHIFT)
#define HACC_LOCAL_MMIO_ERR_BCAST_READ_MASK     HACC_BIT32(HACC_LOCAL_MMIO_ERR_BCAST_READ_SHIFT)
#define HACC_LOCAL_MMIO_ERR_TARGET_BUS_MASK     HACC_BIT32(HACC_LOCAL_MMIO_ERR_TARGET_BUS_SHIFT)
#define HACC_LOCAL_MMIO_ERR_TIMEOUT_MASK        HACC_BIT32(HACC_LOCAL_MMIO_ERR_TIMEOUT_SHIFT)

/* Core-local timer/MSIP MMIO offsets */
#define HACC_TIMER_REG_MSIP                     UINT32_C(0x000)
#define HACC_TIMER_REG_MTIMECMP_LO              UINT32_C(0x004)
#define HACC_TIMER_REG_MTIMECMP_HI              UINT32_C(0x008)
#define HACC_TIMER_REG_MTIME_LO                 UINT32_C(0x00C)
#define HACC_TIMER_REG_MTIME_HI                 UINT32_C(0x010)
#define HACC_TIMER_REG_TIMER_CTRL               UINT32_C(0x014)

#define HACC_TIMER_CTRL_EN_SHIFT                0u
#define HACC_TIMER_CTRL_EN_MASK                 HACC_BIT32(HACC_TIMER_CTRL_EN_SHIFT)

/* DMA MMIO offsets — unified 4D mode */
#define HACC_DMA_REG_CAP0                       UINT32_C(0x000)
#define HACC_DMA_REG_STATUS                     UINT32_C(0x004)
#define HACC_DMA_REG_CTRL                       UINT32_C(0x008)
#define HACC_DMA_REG_SRC_KIND                   UINT32_C(0x00C)
#define HACC_DMA_REG_DST_KIND                   UINT32_C(0x010)
#define HACC_DMA_REG_SRC_ADDR_LO                UINT32_C(0x014)
#define HACC_DMA_REG_SRC_ADDR_HI                UINT32_C(0x018)
#define HACC_DMA_REG_DST_ADDR_LO                UINT32_C(0x01C)
#define HACC_DMA_REG_DST_ADDR_HI                UINT32_C(0x020)
#define HACC_DMA_REG_SRC_CLUSTER_ID             UINT32_C(0x024)
#define HACC_DMA_REG_DST_CLUSTER_ID             UINT32_C(0x028)
#define HACC_DMA_REG_COUNT_D0                   UINT32_C(0x02C)
#define HACC_DMA_REG_COUNT_D1                   UINT32_C(0x030)
#define HACC_DMA_REG_COUNT_D2                   UINT32_C(0x034)
#define HACC_DMA_REG_COUNT_D3                   UINT32_C(0x038)
#define HACC_DMA_REG_SRC_STRIDE_D0              UINT32_C(0x03C)
#define HACC_DMA_REG_SRC_STRIDE_D1              UINT32_C(0x040)
#define HACC_DMA_REG_SRC_STRIDE_D2              UINT32_C(0x044)
#define HACC_DMA_REG_SRC_STRIDE_D3              UINT32_C(0x048)
#define HACC_DMA_REG_DST_STRIDE_D0              UINT32_C(0x04C)
#define HACC_DMA_REG_DST_STRIDE_D1              UINT32_C(0x050)
#define HACC_DMA_REG_DST_STRIDE_D2              UINT32_C(0x054)
#define HACC_DMA_REG_DST_STRIDE_D3              UINT32_C(0x058)
#define HACC_DMA_REG_CMD_TAG                    UINT32_C(0x05C)
#define HACC_DMA_REG_DONE_TAG                   UINT32_C(0x060)
#define HACC_DMA_REG_ERR_CODE                   UINT32_C(0x064)
#define HACC_DMA_REG_ERR_INFO                   UINT32_C(0x068)
#define HACC_DMA_REG_DEBUG_STATE                UINT32_C(0x06C)
#define HACC_DMA_REG_XFORM_CTRL                 UINT32_C(0x070)
#define HACC_DMA_REG_PAD_WINDOW_H0             UINT32_C(0x074)
#define HACC_DMA_REG_PAD_WINDOW_W0             UINT32_C(0x078)
#define HACC_DMA_REG_PAD_SRC_H                 UINT32_C(0x07C)
#define HACC_DMA_REG_PAD_SRC_W                 UINT32_C(0x080)
#define HACC_DMA_REG_BEATS_PER_PIXEL           UINT32_C(0x084)
#define HACC_DMA_REG_FILL_VALUE_LO             UINT32_C(0x088)
#define HACC_DMA_REG_FILL_VALUE_HI             UINT32_C(0x08C)
#define HACC_DMA_REG_EPILOGUE_CTRL             UINT32_C(0x090)
#define HACC_DMA_REG_EPILOGUE_PARAM0           UINT32_C(0x094)

/* DMA_STATUS bits */
#define HACC_DMA_STATUS_IDLE_SHIFT              0u
#define HACC_DMA_STATUS_BUSY_SHIFT              1u
#define HACC_DMA_STATUS_CMD_FIFO_FULL_SHIFT     2u
#define HACC_DMA_STATUS_DONE_PENDING_SHIFT      3u
#define HACC_DMA_STATUS_ERR_PENDING_SHIFT       4u
#define HACC_DMA_STATUS_FATAL_SHIFT             5u

#define HACC_DMA_STATUS_IDLE_MASK               HACC_BIT32(HACC_DMA_STATUS_IDLE_SHIFT)
#define HACC_DMA_STATUS_BUSY_MASK               HACC_BIT32(HACC_DMA_STATUS_BUSY_SHIFT)
#define HACC_DMA_STATUS_CMD_FIFO_FULL_MASK      HACC_BIT32(HACC_DMA_STATUS_CMD_FIFO_FULL_SHIFT)
#define HACC_DMA_STATUS_DONE_PENDING_MASK       HACC_BIT32(HACC_DMA_STATUS_DONE_PENDING_SHIFT)
#define HACC_DMA_STATUS_ERR_PENDING_MASK        HACC_BIT32(HACC_DMA_STATUS_ERR_PENDING_SHIFT)
#define HACC_DMA_STATUS_FATAL_MASK              HACC_BIT32(HACC_DMA_STATUS_FATAL_SHIFT)

/* DMA_CTRL bits */
#define HACC_DMA_CTRL_SUBMIT_SHIFT              0u
#define HACC_DMA_CTRL_ABORT_SHIFT               1u
#define HACC_DMA_CTRL_SOFT_RESET_SHIFT          2u
#define HACC_DMA_CTRL_IRQ_EN_SHIFT              3u

#define HACC_DMA_CTRL_SUBMIT_MASK               HACC_BIT32(HACC_DMA_CTRL_SUBMIT_SHIFT)
#define HACC_DMA_CTRL_ABORT_MASK                HACC_BIT32(HACC_DMA_CTRL_ABORT_SHIFT)
#define HACC_DMA_CTRL_SOFT_RESET_MASK           HACC_BIT32(HACC_DMA_CTRL_SOFT_RESET_SHIFT)
#define HACC_DMA_CTRL_IRQ_EN_MASK               HACC_BIT32(HACC_DMA_CTRL_IRQ_EN_SHIFT)

/* DMA transform control */
#define HACC_DMA_XFORM_LOAD_PAD_EN_SHIFT        0u
#define HACC_DMA_XFORM_LOAD_PAD_EN_MASK         HACC_BIT32(HACC_DMA_XFORM_LOAD_PAD_EN_SHIFT)
#define HACC_DMA_XFORM_FILL_MODE_SHIFT          4u
#define HACC_DMA_XFORM_FILL_MODE_MASK           (UINT32_C(0x3) << HACC_DMA_XFORM_FILL_MODE_SHIFT)

#define HACC_DMA_XFORM_FILL_ZERO                UINT32_C(0)
#define HACC_DMA_XFORM_FILL_EPSILON             UINT32_C(1)
#define HACC_DMA_XFORM_FILL_CONST               UINT32_C(2)

#define HACC_DMA_EPILOGUE_MODE_SHIFT            0u
#define HACC_DMA_EPILOGUE_MODE_MASK             (UINT32_C(0x3) << HACC_DMA_EPILOGUE_MODE_SHIFT)
#define HACC_DMA_EPILOGUE_NONE                  UINT32_C(0)
#define HACC_DMA_EPILOGUE_RELU                  UINT32_C(1)

/* DMA endpoint kinds */
#define HACC_DMA_ENDPOINT_DRAM                  UINT32_C(0)
#define HACC_DMA_ENDPOINT_CLUSTER_SPM           UINT32_C(1)

/* DMA error codes */
#define HACC_DMA_ERR_NONE                       UINT32_C(0)
#define HACC_DMA_ERR_SUBMIT_WHEN_FULL           UINT32_C(1)
#define HACC_DMA_ERR_BAD_ENDPOINT_KIND          UINT32_C(2)
#define HACC_DMA_ERR_ADDR_ALIGN                 UINT32_C(3)
#define HACC_DMA_ERR_ZERO_LENGTH                UINT32_C(4)
#define HACC_DMA_ERR_CLUSTER_RESP               UINT32_C(5)
#define HACC_DMA_ERR_DRAM_AXI                   UINT32_C(6)
#define HACC_DMA_ERR_ABORTED                    UINT32_C(7)
#define HACC_DMA_ERR_BAD_XFORM                  UINT32_C(8)

/* PLIC MMIO offsets */
#define HACC_PLIC_REG_PRIORITY_BASE             UINT32_C(0x0000)
#define HACC_PLIC_REG_PENDING_LO                UINT32_C(0x0800)
#define HACC_PLIC_REG_PENDING_HI                UINT32_C(0x0804)
#define HACC_PLIC_REG_ENABLE_LO                 UINT32_C(0x1000)
#define HACC_PLIC_REG_ENABLE_HI                 UINT32_C(0x1004)
#define HACC_PLIC_REG_THRESHOLD                 UINT32_C(0x1800)
#define HACC_PLIC_REG_CLAIM_COMPLETE            UINT32_C(0x1804)
#define HACC_PLIC_REG_MAX_SOURCE_ID             UINT32_C(0x1808)

static inline uint32_t hacc_plic_priority_offset(uint32_t source_id) {
	return HACC_PLIC_REG_PRIORITY_BASE + (UINT32_C(4) * source_id);
}

static inline uint32_t hacc_plic_cluster_src_id(uint32_t cluster_id) {
	return UINT32_C(1) + cluster_id;
}

static inline uint32_t hacc_plic_dma_src_id(uint32_t num_clusters) {
	return UINT32_C(1) + num_clusters;
}

static inline uint32_t hacc_plic_nlu_src_id(uint32_t num_clusters, uint32_t nlu_id) {
	return num_clusters + UINT32_C(2) + nlu_id;
}

static inline uint32_t hacc_plic_loader_fault_src_id(uint32_t num_clusters, uint32_t num_nlu) {
	return num_clusters + num_nlu + UINT32_C(2);
}

static inline uint32_t hacc_plic_fabric_fault_src_id(uint32_t num_clusters, uint32_t num_nlu) {
	return num_clusters + num_nlu + UINT32_C(3);
}

static inline uint32_t hacc_plic_num_sources(uint32_t num_clusters, uint32_t num_nlu) {
	return num_clusters + num_nlu + UINT32_C(3);
}

#endif