#!/usr/bin/env python3
"""
Perfetto Trace Analyzer for HybridAcc ESL Simulation.

Reads Chrome Trace Event Format JSON files generated by the ESL simulator
and produces:
  1. Phase time breakdown (host_configure, section_load, core_running, dma_transfer)
  2. DMA transfer statistics (#transfers, total cycles, avg/min/max per transfer)
  3. Timeline summary table
  4. Optional CSV export

Usage:
    python analyze_trace.py trace.json
    python analyze_trace.py trace.json --csv output.csv
    python analyze_trace.py trace.json --plot  # requires matplotlib
"""

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any


def load_trace(path: str) -> list[dict[str, Any]]:
    """Load Chrome Trace Event JSON and return the event list."""
    with open(path) as f:
        data = json.load(f)
    if isinstance(data, dict):
        return data.get("traceEvents", [])
    return data


def match_begin_end(events: list[dict]) -> list[dict]:
    """
    Match B/E event pairs into duration spans.
    Returns list of {cat, name, pid, tid, start_us, end_us, dur_us}.
    """
    open_stack: dict[tuple, list] = defaultdict(list)  # (pid, tid, cat, name) → [ts...]
    spans = []

    for ev in events:
        ph = ev.get("ph")
        if ph == "M":
            continue
        key = (ev.get("pid", 0), ev.get("tid", 0), ev.get("cat", ""), ev.get("name", ""))
        ts = ev.get("ts", 0)

        if ph == "B":
            open_stack[key].append(ts)
        elif ph == "E":
            stack = open_stack[key]
            if stack:
                begin_ts = stack.pop()
                spans.append({
                    "cat":      key[2],
                    "name":     key[3],
                    "pid":      key[0],
                    "tid":      key[1],
                    "start_us": begin_ts,
                    "end_us":   ts,
                    "dur_us":   ts - begin_ts,
                })
        elif ph == "X":
            dur = ev.get("dur", 0)
            spans.append({
                "cat":      ev.get("cat", ""),
                "name":     ev.get("name", ""),
                "pid":      ev.get("pid", 0),
                "tid":      ev.get("tid", 0),
                "start_us": ts,
                "end_us":   ts + dur,
                "dur_us":   dur,
            })

    return spans


def analyze(spans: list[dict], clock_period_ns: float = 10.0) -> dict:
    """
    Produce analysis from matched trace spans.
    clock_period_ns: SystemC clock period in nanoseconds (default 10ns = 100MHz).
    Returns a dict with phase_breakdown, dma_stats, and timeline.
    """
    us_per_cycle = clock_period_ns / 1000.0

    # Phase breakdown (top-level core phases)
    core_phases = ["host_configure", "wait_loader", "section_load", "core_running"]
    phase_map: dict[str, list[dict]] = defaultdict(list)
    for s in spans:
        if s["name"] in core_phases:
            phase_map[s["name"]].append(s)

    phase_breakdown = {}
    for name in core_phases:
        items = phase_map.get(name, [])
        total_us = sum(s["dur_us"] for s in items)
        total_cycles = total_us / us_per_cycle if us_per_cycle else 0
        phase_breakdown[name] = {
            "total_us":     total_us,
            "total_cycles": int(round(total_cycles)),
            "count":        len(items),
        }

    # DMA stats
    dma_spans = [s for s in spans if s["name"] == "dma_transfer"]
    dma_durs = [s["dur_us"] for s in dma_spans]
    dma_stats = {
        "count":       len(dma_spans),
        "total_us":    sum(dma_durs) if dma_durs else 0,
        "total_cycles": int(round(sum(dma_durs) / us_per_cycle)) if dma_durs else 0,
        "avg_us":      sum(dma_durs) / len(dma_durs) if dma_durs else 0,
        "min_us":      min(dma_durs) if dma_durs else 0,
        "max_us":      max(dma_durs) if dma_durs else 0,
        "avg_cycles":  int(round(sum(dma_durs) / len(dma_durs) / us_per_cycle)) if dma_durs else 0,
    }

    # Overall timeline
    all_ts = [s["start_us"] for s in spans] + [s["end_us"] for s in spans]
    sim_start = min(all_ts) if all_ts else 0
    sim_end = max(all_ts) if all_ts else 0
    total_sim_us = sim_end - sim_start
    total_sim_cycles = int(round(total_sim_us / us_per_cycle)) if us_per_cycle else 0

    # Time proportions
    proportions = {}
    if total_sim_us > 0:
        for name, info in phase_breakdown.items():
            proportions[name] = info["total_us"] / total_sim_us * 100
        proportions["dma_transfer"] = dma_stats["total_us"] / total_sim_us * 100

    return {
        "phase_breakdown": phase_breakdown,
        "dma_stats":       dma_stats,
        "total_sim_us":    total_sim_us,
        "total_sim_cycles": total_sim_cycles,
        "proportions":     proportions,
        "all_spans":       spans,
    }


def print_report(result: dict):
    """Print a human-readable report to stdout."""
    print("=" * 70)
    print("  HybridAcc ESL Trace Analysis Report")
    print("=" * 70)

    print(f"\nTotal simulation: {result['total_sim_us']:.1f} µs"
          f"  ({result['total_sim_cycles']} cycles)")

    print("\n--- Phase Time Breakdown ---")
    print(f"  {'Phase':<20s} {'Cycles':>10s} {'Time (µs)':>12s} {'Proportion':>12s}")
    print("  " + "-" * 56)
    for name, info in result["phase_breakdown"].items():
        pct = result["proportions"].get(name, 0)
        print(f"  {name:<20s} {info['total_cycles']:>10d} {info['total_us']:>12.1f} {pct:>11.1f}%")

    print("\n--- DMA Statistics ---")
    ds = result["dma_stats"]
    print(f"  Transfers:     {ds['count']}")
    print(f"  Total cycles:  {ds['total_cycles']}")
    print(f"  Total time:    {ds['total_us']:.1f} µs")
    if ds["count"] > 0:
        print(f"  Avg per xfer:  {ds['avg_cycles']} cycles ({ds['avg_us']:.1f} µs)")
        print(f"  Min per xfer:  {ds['min_us']:.1f} µs")
        print(f"  Max per xfer:  {ds['max_us']:.1f} µs")
        pct = result["proportions"].get("dma_transfer", 0)
        print(f"  DMA proportion: {pct:.1f}% of total simulation")

    print("\n" + "=" * 70)


def export_csv(result: dict, path: str):
    """Export analysis to CSV."""
    import csv
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["metric", "value", "unit"])
        w.writerow(["total_sim_cycles", result["total_sim_cycles"], "cycles"])
        w.writerow(["total_sim_us", f"{result['total_sim_us']:.1f}", "µs"])
        for name, info in result["phase_breakdown"].items():
            w.writerow([f"phase_{name}_cycles", info["total_cycles"], "cycles"])
            w.writerow([f"phase_{name}_us", f"{info['total_us']:.1f}", "µs"])
            w.writerow([f"phase_{name}_pct", f"{result['proportions'].get(name, 0):.1f}", "%"])
        ds = result["dma_stats"]
        w.writerow(["dma_count", ds["count"], "transfers"])
        w.writerow(["dma_total_cycles", ds["total_cycles"], "cycles"])
        w.writerow(["dma_avg_cycles", ds["avg_cycles"], "cycles"])
    print(f"[CSV] Written to {path}")


def plot_breakdown(result: dict, output: str | None = None):
    """Plot phase time breakdown as a pie chart."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed, skipping plot", file=sys.stderr)
        return

    labels = []
    sizes = []
    for name, pct in result["proportions"].items():
        if pct > 0.1:
            labels.append(name)
            sizes.append(pct)

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.pie(sizes, labels=labels, autopct="%1.1f%%", startangle=90)
    ax.set_title("HybridAcc Simulation Phase Breakdown")
    if output:
        plt.savefig(output, dpi=150, bbox_inches="tight")
        print(f"[Plot] Saved to {output}")
    else:
        plt.show()


def main():
    parser = argparse.ArgumentParser(description="Analyze HybridAcc ESL trace files")
    parser.add_argument("trace_file", help="Path to trace JSON file")
    parser.add_argument("--csv", metavar="FILE", help="Export analysis to CSV")
    parser.add_argument("--plot", action="store_true", help="Show pie chart (requires matplotlib)")
    parser.add_argument("--plot-output", metavar="FILE", help="Save pie chart to file")
    parser.add_argument("--clock-period", type=float, default=10.0,
                        help="Clock period in nanoseconds (default: 10.0 = 100MHz)")
    parser.add_argument("--json", action="store_true", help="Output analysis as JSON")
    args = parser.parse_args()

    events = load_trace(args.trace_file)
    spans = match_begin_end(events)
    result = analyze(spans, clock_period_ns=args.clock_period)

    if args.json:
        out = {k: v for k, v in result.items() if k != "all_spans"}
        json.dump(out, sys.stdout, indent=2)
        print()
    else:
        print_report(result)

    if args.csv:
        export_csv(result, args.csv)

    if args.plot or args.plot_output:
        plot_breakdown(result, args.plot_output)


if __name__ == "__main__":
    main()
